// Code generated by ent, DO NOT EDIT.

package merchantwithdrawrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldID, id))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldMerchantID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldStatus, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentAccount applies equality check predicate on the "payment_account" field. It's identical to PaymentAccountEQ.
func PaymentAccount(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentAccount, v))
}

// PaymentName applies equality check predicate on the "payment_name" field. It's identical to PaymentNameEQ.
func PaymentName(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentName, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldNote, v))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldAdminID, v))
}

// RejectReason applies equality check predicate on the "reject_reason" field. It's identical to RejectReasonEQ.
func RejectReason(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldRejectReason, v))
}

// LedgerID applies equality check predicate on the "ledger_id" field. It's identical to LedgerIDEQ.
func LedgerID(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldLedgerID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldProcessedAt, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldMerchantID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldStatus, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// PaymentAccountEQ applies the EQ predicate on the "payment_account" field.
func PaymentAccountEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentAccount, v))
}

// PaymentAccountNEQ applies the NEQ predicate on the "payment_account" field.
func PaymentAccountNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldPaymentAccount, v))
}

// PaymentAccountIn applies the In predicate on the "payment_account" field.
func PaymentAccountIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldPaymentAccount, vs...))
}

// PaymentAccountNotIn applies the NotIn predicate on the "payment_account" field.
func PaymentAccountNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldPaymentAccount, vs...))
}

// PaymentAccountGT applies the GT predicate on the "payment_account" field.
func PaymentAccountGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldPaymentAccount, v))
}

// PaymentAccountGTE applies the GTE predicate on the "payment_account" field.
func PaymentAccountGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldPaymentAccount, v))
}

// PaymentAccountLT applies the LT predicate on the "payment_account" field.
func PaymentAccountLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldPaymentAccount, v))
}

// PaymentAccountLTE applies the LTE predicate on the "payment_account" field.
func PaymentAccountLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldPaymentAccount, v))
}

// PaymentAccountContains applies the Contains predicate on the "payment_account" field.
func PaymentAccountContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldPaymentAccount, v))
}

// PaymentAccountHasPrefix applies the HasPrefix predicate on the "payment_account" field.
func PaymentAccountHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldPaymentAccount, v))
}

// PaymentAccountHasSuffix applies the HasSuffix predicate on the "payment_account" field.
func PaymentAccountHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldPaymentAccount, v))
}

// PaymentAccountEqualFold applies the EqualFold predicate on the "payment_account" field.
func PaymentAccountEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldPaymentAccount, v))
}

// PaymentAccountContainsFold applies the ContainsFold predicate on the "payment_account" field.
func PaymentAccountContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldPaymentAccount, v))
}

// PaymentNameEQ applies the EQ predicate on the "payment_name" field.
func PaymentNameEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldPaymentName, v))
}

// PaymentNameNEQ applies the NEQ predicate on the "payment_name" field.
func PaymentNameNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldPaymentName, v))
}

// PaymentNameIn applies the In predicate on the "payment_name" field.
func PaymentNameIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldPaymentName, vs...))
}

// PaymentNameNotIn applies the NotIn predicate on the "payment_name" field.
func PaymentNameNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldPaymentName, vs...))
}

// PaymentNameGT applies the GT predicate on the "payment_name" field.
func PaymentNameGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldPaymentName, v))
}

// PaymentNameGTE applies the GTE predicate on the "payment_name" field.
func PaymentNameGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldPaymentName, v))
}

// PaymentNameLT applies the LT predicate on the "payment_name" field.
func PaymentNameLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldPaymentName, v))
}

// PaymentNameLTE applies the LTE predicate on the "payment_name" field.
func PaymentNameLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldPaymentName, v))
}

// PaymentNameContains applies the Contains predicate on the "payment_name" field.
func PaymentNameContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldPaymentName, v))
}

// PaymentNameHasPrefix applies the HasPrefix predicate on the "payment_name" field.
func PaymentNameHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldPaymentName, v))
}

// PaymentNameHasSuffix applies the HasSuffix predicate on the "payment_name" field.
func PaymentNameHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldPaymentName, v))
}

// PaymentNameEqualFold applies the EqualFold predicate on the "payment_name" field.
func PaymentNameEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldPaymentName, v))
}

// PaymentNameContainsFold applies the ContainsFold predicate on the "payment_name" field.
func PaymentNameContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldPaymentName, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldNote, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldAdminID, v))
}

// AdminIDIsNil applies the IsNil predicate on the "admin_id" field.
func AdminIDIsNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIsNull(FieldAdminID))
}

// AdminIDNotNil applies the NotNil predicate on the "admin_id" field.
func AdminIDNotNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotNull(FieldAdminID))
}

// RejectReasonEQ applies the EQ predicate on the "reject_reason" field.
func RejectReasonEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldRejectReason, v))
}

// RejectReasonNEQ applies the NEQ predicate on the "reject_reason" field.
func RejectReasonNEQ(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldRejectReason, v))
}

// RejectReasonIn applies the In predicate on the "reject_reason" field.
func RejectReasonIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldRejectReason, vs...))
}

// RejectReasonNotIn applies the NotIn predicate on the "reject_reason" field.
func RejectReasonNotIn(vs ...string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldRejectReason, vs...))
}

// RejectReasonGT applies the GT predicate on the "reject_reason" field.
func RejectReasonGT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldRejectReason, v))
}

// RejectReasonGTE applies the GTE predicate on the "reject_reason" field.
func RejectReasonGTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldRejectReason, v))
}

// RejectReasonLT applies the LT predicate on the "reject_reason" field.
func RejectReasonLT(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldRejectReason, v))
}

// RejectReasonLTE applies the LTE predicate on the "reject_reason" field.
func RejectReasonLTE(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldRejectReason, v))
}

// RejectReasonContains applies the Contains predicate on the "reject_reason" field.
func RejectReasonContains(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContains(FieldRejectReason, v))
}

// RejectReasonHasPrefix applies the HasPrefix predicate on the "reject_reason" field.
func RejectReasonHasPrefix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasPrefix(FieldRejectReason, v))
}

// RejectReasonHasSuffix applies the HasSuffix predicate on the "reject_reason" field.
func RejectReasonHasSuffix(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldHasSuffix(FieldRejectReason, v))
}

// RejectReasonEqualFold applies the EqualFold predicate on the "reject_reason" field.
func RejectReasonEqualFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEqualFold(FieldRejectReason, v))
}

// RejectReasonContainsFold applies the ContainsFold predicate on the "reject_reason" field.
func RejectReasonContainsFold(v string) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldContainsFold(FieldRejectReason, v))
}

// LedgerIDEQ applies the EQ predicate on the "ledger_id" field.
func LedgerIDEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldLedgerID, v))
}

// LedgerIDNEQ applies the NEQ predicate on the "ledger_id" field.
func LedgerIDNEQ(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldLedgerID, v))
}

// LedgerIDIn applies the In predicate on the "ledger_id" field.
func LedgerIDIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldLedgerID, vs...))
}

// LedgerIDNotIn applies the NotIn predicate on the "ledger_id" field.
func LedgerIDNotIn(vs ...int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldLedgerID, vs...))
}

// LedgerIDGT applies the GT predicate on the "ledger_id" field.
func LedgerIDGT(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldLedgerID, v))
}

// LedgerIDGTE applies the GTE predicate on the "ledger_id" field.
func LedgerIDGTE(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldLedgerID, v))
}

// LedgerIDLT applies the LT predicate on the "ledger_id" field.
func LedgerIDLT(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldLedgerID, v))
}

// LedgerIDLTE applies the LTE predicate on the "ledger_id" field.
func LedgerIDLTE(v int64) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldLedgerID, v))
}

// LedgerIDIsNil applies the IsNil predicate on the "ledger_id" field.
func LedgerIDIsNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIsNull(FieldLedgerID))
}

// LedgerIDNotNil applies the NotNil predicate on the "ledger_id" field.
func LedgerIDNotNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotNull(FieldLedgerID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.FieldNotNull(FieldProcessedAt))
}

// HasMerchant applies the HasEdge predicate on the "merchant" edge.
func HasMerchant() predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantWith applies the HasEdge predicate on the "merchant" edge with a given conditions (other predicates).
func HasMerchantWith(preds ...predicate.Merchant) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(func(s *sql.Selector) {
		step := newMerchantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantWithdrawRequest) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantWithdrawRequest) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantWithdrawRequest) predicate.MerchantWithdrawRequest {
	return predicate.MerchantWithdrawRequest(sql.NotPredicates(p))
}
