// Code generated by ent, DO NOT EDIT.

package merchantdomain

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the merchantdomain type in the database.
	Label = "merchant_domain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldMerchantID holds the string denoting the merchant_id field in the database.
	FieldMerchantID = "merchant_id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldSiteName holds the string denoting the site_name field in the database.
	FieldSiteName = "site_name"
	// FieldSiteLogo holds the string denoting the site_logo field in the database.
	FieldSiteLogo = "site_logo"
	// FieldBrandColor holds the string denoting the brand_color field in the database.
	FieldBrandColor = "brand_color"
	// FieldCustomCSS holds the string denoting the custom_css field in the database.
	FieldCustomCSS = "custom_css"
	// FieldHomeContent holds the string denoting the home_content field in the database.
	FieldHomeContent = "home_content"
	// FieldSeoTitle holds the string denoting the seo_title field in the database.
	FieldSeoTitle = "seo_title"
	// FieldSeoDescription holds the string denoting the seo_description field in the database.
	FieldSeoDescription = "seo_description"
	// FieldSeoKeywords holds the string denoting the seo_keywords field in the database.
	FieldSeoKeywords = "seo_keywords"
	// FieldVerifyToken holds the string denoting the verify_token field in the database.
	FieldVerifyToken = "verify_token"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// EdgeMerchant holds the string denoting the merchant edge name in mutations.
	EdgeMerchant = "merchant"
	// Table holds the table name of the merchantdomain in the database.
	Table = "merchant_domains"
	// MerchantTable is the table that holds the merchant relation/edge.
	MerchantTable = "merchant_domains"
	// MerchantInverseTable is the table name for the Merchant entity.
	// It exists in this package in order to avoid circular dependency with the "merchant" package.
	MerchantInverseTable = "merchants"
	// MerchantColumn is the table column denoting the merchant relation/edge.
	MerchantColumn = "merchant_id"
)

// Columns holds all SQL columns for merchantdomain fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldMerchantID,
	FieldDomain,
	FieldSiteName,
	FieldSiteLogo,
	FieldBrandColor,
	FieldCustomCSS,
	FieldHomeContent,
	FieldSeoTitle,
	FieldSeoDescription,
	FieldSeoKeywords,
	FieldVerifyToken,
	FieldVerified,
	FieldVerifiedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// DefaultSiteName holds the default value on creation for the "site_name" field.
	DefaultSiteName string
	// SiteNameValidator is a validator for the "site_name" field. It is called by the builders before save.
	SiteNameValidator func(string) error
	// DefaultSiteLogo holds the default value on creation for the "site_logo" field.
	DefaultSiteLogo string
	// DefaultBrandColor holds the default value on creation for the "brand_color" field.
	DefaultBrandColor string
	// BrandColorValidator is a validator for the "brand_color" field. It is called by the builders before save.
	BrandColorValidator func(string) error
	// DefaultCustomCSS holds the default value on creation for the "custom_css" field.
	DefaultCustomCSS string
	// DefaultHomeContent holds the default value on creation for the "home_content" field.
	DefaultHomeContent string
	// DefaultSeoTitle holds the default value on creation for the "seo_title" field.
	DefaultSeoTitle string
	// SeoTitleValidator is a validator for the "seo_title" field. It is called by the builders before save.
	SeoTitleValidator func(string) error
	// DefaultSeoDescription holds the default value on creation for the "seo_description" field.
	DefaultSeoDescription string
	// DefaultSeoKeywords holds the default value on creation for the "seo_keywords" field.
	DefaultSeoKeywords string
	// SeoKeywordsValidator is a validator for the "seo_keywords" field. It is called by the builders before save.
	SeoKeywordsValidator func(string) error
	// DefaultVerifyToken holds the default value on creation for the "verify_token" field.
	DefaultVerifyToken string
	// VerifyTokenValidator is a validator for the "verify_token" field. It is called by the builders before save.
	VerifyTokenValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
)

// OrderOption defines the ordering options for the MerchantDomain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByMerchantID orders the results by the merchant_id field.
func ByMerchantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantID, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// BySiteName orders the results by the site_name field.
func BySiteName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteName, opts...).ToFunc()
}

// BySiteLogo orders the results by the site_logo field.
func BySiteLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteLogo, opts...).ToFunc()
}

// ByBrandColor orders the results by the brand_color field.
func ByBrandColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrandColor, opts...).ToFunc()
}

// ByCustomCSS orders the results by the custom_css field.
func ByCustomCSS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomCSS, opts...).ToFunc()
}

// ByHomeContent orders the results by the home_content field.
func ByHomeContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomeContent, opts...).ToFunc()
}

// BySeoTitle orders the results by the seo_title field.
func BySeoTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoTitle, opts...).ToFunc()
}

// BySeoDescription orders the results by the seo_description field.
func BySeoDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoDescription, opts...).ToFunc()
}

// BySeoKeywords orders the results by the seo_keywords field.
func BySeoKeywords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoKeywords, opts...).ToFunc()
}

// ByVerifyToken orders the results by the verify_token field.
func ByVerifyToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifyToken, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByMerchantField orders the results by merchant field.
func ByMerchantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMerchantStep(), sql.OrderByField(field, opts...))
	}
}
func newMerchantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MerchantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
	)
}
