// Code generated by ent, DO NOT EDIT.

package merchantdomain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldDeletedAt, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldMerchantID, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldDomain, v))
}

// SiteName applies equality check predicate on the "site_name" field. It's identical to SiteNameEQ.
func SiteName(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSiteName, v))
}

// SiteLogo applies equality check predicate on the "site_logo" field. It's identical to SiteLogoEQ.
func SiteLogo(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSiteLogo, v))
}

// BrandColor applies equality check predicate on the "brand_color" field. It's identical to BrandColorEQ.
func BrandColor(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldBrandColor, v))
}

// CustomCSS applies equality check predicate on the "custom_css" field. It's identical to CustomCSSEQ.
func CustomCSS(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldCustomCSS, v))
}

// HomeContent applies equality check predicate on the "home_content" field. It's identical to HomeContentEQ.
func HomeContent(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldHomeContent, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoDescription applies equality check predicate on the "seo_description" field. It's identical to SeoDescriptionEQ.
func SeoDescription(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoDescription, v))
}

// SeoKeywords applies equality check predicate on the "seo_keywords" field. It's identical to SeoKeywordsEQ.
func SeoKeywords(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoKeywords, v))
}

// VerifyToken applies equality check predicate on the "verify_token" field. It's identical to VerifyTokenEQ.
func VerifyToken(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerifyToken, v))
}

// Verified applies equality check predicate on the "verified" field. It's identical to VerifiedEQ.
func Verified(v bool) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerified, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerifiedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotNull(FieldDeletedAt))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldMerchantID, vs...))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldDomain, v))
}

// SiteNameEQ applies the EQ predicate on the "site_name" field.
func SiteNameEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSiteName, v))
}

// SiteNameNEQ applies the NEQ predicate on the "site_name" field.
func SiteNameNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldSiteName, v))
}

// SiteNameIn applies the In predicate on the "site_name" field.
func SiteNameIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldSiteName, vs...))
}

// SiteNameNotIn applies the NotIn predicate on the "site_name" field.
func SiteNameNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldSiteName, vs...))
}

// SiteNameGT applies the GT predicate on the "site_name" field.
func SiteNameGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldSiteName, v))
}

// SiteNameGTE applies the GTE predicate on the "site_name" field.
func SiteNameGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldSiteName, v))
}

// SiteNameLT applies the LT predicate on the "site_name" field.
func SiteNameLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldSiteName, v))
}

// SiteNameLTE applies the LTE predicate on the "site_name" field.
func SiteNameLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldSiteName, v))
}

// SiteNameContains applies the Contains predicate on the "site_name" field.
func SiteNameContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldSiteName, v))
}

// SiteNameHasPrefix applies the HasPrefix predicate on the "site_name" field.
func SiteNameHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldSiteName, v))
}

// SiteNameHasSuffix applies the HasSuffix predicate on the "site_name" field.
func SiteNameHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldSiteName, v))
}

// SiteNameEqualFold applies the EqualFold predicate on the "site_name" field.
func SiteNameEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldSiteName, v))
}

// SiteNameContainsFold applies the ContainsFold predicate on the "site_name" field.
func SiteNameContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldSiteName, v))
}

// SiteLogoEQ applies the EQ predicate on the "site_logo" field.
func SiteLogoEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSiteLogo, v))
}

// SiteLogoNEQ applies the NEQ predicate on the "site_logo" field.
func SiteLogoNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldSiteLogo, v))
}

// SiteLogoIn applies the In predicate on the "site_logo" field.
func SiteLogoIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldSiteLogo, vs...))
}

// SiteLogoNotIn applies the NotIn predicate on the "site_logo" field.
func SiteLogoNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldSiteLogo, vs...))
}

// SiteLogoGT applies the GT predicate on the "site_logo" field.
func SiteLogoGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldSiteLogo, v))
}

// SiteLogoGTE applies the GTE predicate on the "site_logo" field.
func SiteLogoGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldSiteLogo, v))
}

// SiteLogoLT applies the LT predicate on the "site_logo" field.
func SiteLogoLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldSiteLogo, v))
}

// SiteLogoLTE applies the LTE predicate on the "site_logo" field.
func SiteLogoLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldSiteLogo, v))
}

// SiteLogoContains applies the Contains predicate on the "site_logo" field.
func SiteLogoContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldSiteLogo, v))
}

// SiteLogoHasPrefix applies the HasPrefix predicate on the "site_logo" field.
func SiteLogoHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldSiteLogo, v))
}

// SiteLogoHasSuffix applies the HasSuffix predicate on the "site_logo" field.
func SiteLogoHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldSiteLogo, v))
}

// SiteLogoEqualFold applies the EqualFold predicate on the "site_logo" field.
func SiteLogoEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldSiteLogo, v))
}

// SiteLogoContainsFold applies the ContainsFold predicate on the "site_logo" field.
func SiteLogoContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldSiteLogo, v))
}

// BrandColorEQ applies the EQ predicate on the "brand_color" field.
func BrandColorEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldBrandColor, v))
}

// BrandColorNEQ applies the NEQ predicate on the "brand_color" field.
func BrandColorNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldBrandColor, v))
}

// BrandColorIn applies the In predicate on the "brand_color" field.
func BrandColorIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldBrandColor, vs...))
}

// BrandColorNotIn applies the NotIn predicate on the "brand_color" field.
func BrandColorNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldBrandColor, vs...))
}

// BrandColorGT applies the GT predicate on the "brand_color" field.
func BrandColorGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldBrandColor, v))
}

// BrandColorGTE applies the GTE predicate on the "brand_color" field.
func BrandColorGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldBrandColor, v))
}

// BrandColorLT applies the LT predicate on the "brand_color" field.
func BrandColorLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldBrandColor, v))
}

// BrandColorLTE applies the LTE predicate on the "brand_color" field.
func BrandColorLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldBrandColor, v))
}

// BrandColorContains applies the Contains predicate on the "brand_color" field.
func BrandColorContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldBrandColor, v))
}

// BrandColorHasPrefix applies the HasPrefix predicate on the "brand_color" field.
func BrandColorHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldBrandColor, v))
}

// BrandColorHasSuffix applies the HasSuffix predicate on the "brand_color" field.
func BrandColorHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldBrandColor, v))
}

// BrandColorEqualFold applies the EqualFold predicate on the "brand_color" field.
func BrandColorEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldBrandColor, v))
}

// BrandColorContainsFold applies the ContainsFold predicate on the "brand_color" field.
func BrandColorContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldBrandColor, v))
}

// CustomCSSEQ applies the EQ predicate on the "custom_css" field.
func CustomCSSEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldCustomCSS, v))
}

// CustomCSSNEQ applies the NEQ predicate on the "custom_css" field.
func CustomCSSNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldCustomCSS, v))
}

// CustomCSSIn applies the In predicate on the "custom_css" field.
func CustomCSSIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldCustomCSS, vs...))
}

// CustomCSSNotIn applies the NotIn predicate on the "custom_css" field.
func CustomCSSNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldCustomCSS, vs...))
}

// CustomCSSGT applies the GT predicate on the "custom_css" field.
func CustomCSSGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldCustomCSS, v))
}

// CustomCSSGTE applies the GTE predicate on the "custom_css" field.
func CustomCSSGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldCustomCSS, v))
}

// CustomCSSLT applies the LT predicate on the "custom_css" field.
func CustomCSSLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldCustomCSS, v))
}

// CustomCSSLTE applies the LTE predicate on the "custom_css" field.
func CustomCSSLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldCustomCSS, v))
}

// CustomCSSContains applies the Contains predicate on the "custom_css" field.
func CustomCSSContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldCustomCSS, v))
}

// CustomCSSHasPrefix applies the HasPrefix predicate on the "custom_css" field.
func CustomCSSHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldCustomCSS, v))
}

// CustomCSSHasSuffix applies the HasSuffix predicate on the "custom_css" field.
func CustomCSSHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldCustomCSS, v))
}

// CustomCSSEqualFold applies the EqualFold predicate on the "custom_css" field.
func CustomCSSEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldCustomCSS, v))
}

// CustomCSSContainsFold applies the ContainsFold predicate on the "custom_css" field.
func CustomCSSContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldCustomCSS, v))
}

// HomeContentEQ applies the EQ predicate on the "home_content" field.
func HomeContentEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldHomeContent, v))
}

// HomeContentNEQ applies the NEQ predicate on the "home_content" field.
func HomeContentNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldHomeContent, v))
}

// HomeContentIn applies the In predicate on the "home_content" field.
func HomeContentIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldHomeContent, vs...))
}

// HomeContentNotIn applies the NotIn predicate on the "home_content" field.
func HomeContentNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldHomeContent, vs...))
}

// HomeContentGT applies the GT predicate on the "home_content" field.
func HomeContentGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldHomeContent, v))
}

// HomeContentGTE applies the GTE predicate on the "home_content" field.
func HomeContentGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldHomeContent, v))
}

// HomeContentLT applies the LT predicate on the "home_content" field.
func HomeContentLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldHomeContent, v))
}

// HomeContentLTE applies the LTE predicate on the "home_content" field.
func HomeContentLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldHomeContent, v))
}

// HomeContentContains applies the Contains predicate on the "home_content" field.
func HomeContentContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldHomeContent, v))
}

// HomeContentHasPrefix applies the HasPrefix predicate on the "home_content" field.
func HomeContentHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldHomeContent, v))
}

// HomeContentHasSuffix applies the HasSuffix predicate on the "home_content" field.
func HomeContentHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldHomeContent, v))
}

// HomeContentEqualFold applies the EqualFold predicate on the "home_content" field.
func HomeContentEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldHomeContent, v))
}

// HomeContentContainsFold applies the ContainsFold predicate on the "home_content" field.
func HomeContentContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldHomeContent, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldSeoTitle, v))
}

// SeoDescriptionEQ applies the EQ predicate on the "seo_description" field.
func SeoDescriptionEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoDescription, v))
}

// SeoDescriptionNEQ applies the NEQ predicate on the "seo_description" field.
func SeoDescriptionNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldSeoDescription, v))
}

// SeoDescriptionIn applies the In predicate on the "seo_description" field.
func SeoDescriptionIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldSeoDescription, vs...))
}

// SeoDescriptionNotIn applies the NotIn predicate on the "seo_description" field.
func SeoDescriptionNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldSeoDescription, vs...))
}

// SeoDescriptionGT applies the GT predicate on the "seo_description" field.
func SeoDescriptionGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldSeoDescription, v))
}

// SeoDescriptionGTE applies the GTE predicate on the "seo_description" field.
func SeoDescriptionGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldSeoDescription, v))
}

// SeoDescriptionLT applies the LT predicate on the "seo_description" field.
func SeoDescriptionLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldSeoDescription, v))
}

// SeoDescriptionLTE applies the LTE predicate on the "seo_description" field.
func SeoDescriptionLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldSeoDescription, v))
}

// SeoDescriptionContains applies the Contains predicate on the "seo_description" field.
func SeoDescriptionContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldSeoDescription, v))
}

// SeoDescriptionHasPrefix applies the HasPrefix predicate on the "seo_description" field.
func SeoDescriptionHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldSeoDescription, v))
}

// SeoDescriptionHasSuffix applies the HasSuffix predicate on the "seo_description" field.
func SeoDescriptionHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldSeoDescription, v))
}

// SeoDescriptionEqualFold applies the EqualFold predicate on the "seo_description" field.
func SeoDescriptionEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldSeoDescription, v))
}

// SeoDescriptionContainsFold applies the ContainsFold predicate on the "seo_description" field.
func SeoDescriptionContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldSeoDescription, v))
}

// SeoKeywordsEQ applies the EQ predicate on the "seo_keywords" field.
func SeoKeywordsEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldSeoKeywords, v))
}

// SeoKeywordsNEQ applies the NEQ predicate on the "seo_keywords" field.
func SeoKeywordsNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldSeoKeywords, v))
}

// SeoKeywordsIn applies the In predicate on the "seo_keywords" field.
func SeoKeywordsIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldSeoKeywords, vs...))
}

// SeoKeywordsNotIn applies the NotIn predicate on the "seo_keywords" field.
func SeoKeywordsNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldSeoKeywords, vs...))
}

// SeoKeywordsGT applies the GT predicate on the "seo_keywords" field.
func SeoKeywordsGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldSeoKeywords, v))
}

// SeoKeywordsGTE applies the GTE predicate on the "seo_keywords" field.
func SeoKeywordsGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldSeoKeywords, v))
}

// SeoKeywordsLT applies the LT predicate on the "seo_keywords" field.
func SeoKeywordsLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldSeoKeywords, v))
}

// SeoKeywordsLTE applies the LTE predicate on the "seo_keywords" field.
func SeoKeywordsLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldSeoKeywords, v))
}

// SeoKeywordsContains applies the Contains predicate on the "seo_keywords" field.
func SeoKeywordsContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldSeoKeywords, v))
}

// SeoKeywordsHasPrefix applies the HasPrefix predicate on the "seo_keywords" field.
func SeoKeywordsHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldSeoKeywords, v))
}

// SeoKeywordsHasSuffix applies the HasSuffix predicate on the "seo_keywords" field.
func SeoKeywordsHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldSeoKeywords, v))
}

// SeoKeywordsEqualFold applies the EqualFold predicate on the "seo_keywords" field.
func SeoKeywordsEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldSeoKeywords, v))
}

// SeoKeywordsContainsFold applies the ContainsFold predicate on the "seo_keywords" field.
func SeoKeywordsContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldSeoKeywords, v))
}

// VerifyTokenEQ applies the EQ predicate on the "verify_token" field.
func VerifyTokenEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerifyToken, v))
}

// VerifyTokenNEQ applies the NEQ predicate on the "verify_token" field.
func VerifyTokenNEQ(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldVerifyToken, v))
}

// VerifyTokenIn applies the In predicate on the "verify_token" field.
func VerifyTokenIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldVerifyToken, vs...))
}

// VerifyTokenNotIn applies the NotIn predicate on the "verify_token" field.
func VerifyTokenNotIn(vs ...string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldVerifyToken, vs...))
}

// VerifyTokenGT applies the GT predicate on the "verify_token" field.
func VerifyTokenGT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldVerifyToken, v))
}

// VerifyTokenGTE applies the GTE predicate on the "verify_token" field.
func VerifyTokenGTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldVerifyToken, v))
}

// VerifyTokenLT applies the LT predicate on the "verify_token" field.
func VerifyTokenLT(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldVerifyToken, v))
}

// VerifyTokenLTE applies the LTE predicate on the "verify_token" field.
func VerifyTokenLTE(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldVerifyToken, v))
}

// VerifyTokenContains applies the Contains predicate on the "verify_token" field.
func VerifyTokenContains(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContains(FieldVerifyToken, v))
}

// VerifyTokenHasPrefix applies the HasPrefix predicate on the "verify_token" field.
func VerifyTokenHasPrefix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasPrefix(FieldVerifyToken, v))
}

// VerifyTokenHasSuffix applies the HasSuffix predicate on the "verify_token" field.
func VerifyTokenHasSuffix(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldHasSuffix(FieldVerifyToken, v))
}

// VerifyTokenEqualFold applies the EqualFold predicate on the "verify_token" field.
func VerifyTokenEqualFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEqualFold(FieldVerifyToken, v))
}

// VerifyTokenContainsFold applies the ContainsFold predicate on the "verify_token" field.
func VerifyTokenContainsFold(v string) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldContainsFold(FieldVerifyToken, v))
}

// VerifiedEQ applies the EQ predicate on the "verified" field.
func VerifiedEQ(v bool) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerified, v))
}

// VerifiedNEQ applies the NEQ predicate on the "verified" field.
func VerifiedNEQ(v bool) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldVerified, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.FieldNotNull(FieldVerifiedAt))
}

// HasMerchant applies the HasEdge predicate on the "merchant" edge.
func HasMerchant() predicate.MerchantDomain {
	return predicate.MerchantDomain(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantWith applies the HasEdge predicate on the "merchant" edge with a given conditions (other predicates).
func HasMerchantWith(preds ...predicate.Merchant) predicate.MerchantDomain {
	return predicate.MerchantDomain(func(s *sql.Selector) {
		step := newMerchantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantDomain) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantDomain) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantDomain) predicate.MerchantDomain {
	return predicate.MerchantDomain(sql.NotPredicates(p))
}
