// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantwithdrawrequest"
)

// MerchantWithdrawRequest is the model entity for the MerchantWithdrawRequest schema.
type MerchantWithdrawRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// pending / approved / paid / rejected
	Status string `json:"status,omitempty"`
	// alipay / wechat / bank / usdt / other
	PaymentMethod string `json:"payment_method,omitempty"`
	// PaymentAccount holds the value of the "payment_account" field.
	PaymentAccount string `json:"payment_account,omitempty"`
	// PaymentName holds the value of the "payment_name" field.
	PaymentName string `json:"payment_name,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// AdminID holds the value of the "admin_id" field.
	AdminID *int64 `json:"admin_id,omitempty"`
	// RejectReason holds the value of the "reject_reason" field.
	RejectReason string `json:"reject_reason,omitempty"`
	// 批准后写入 merchant_ledger 的 id
	LedgerID *int64 `json:"ledger_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantWithdrawRequestQuery when eager-loading is set.
	Edges        MerchantWithdrawRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantWithdrawRequestEdges holds the relations/edges for other nodes in the graph.
type MerchantWithdrawRequestEdges struct {
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MerchantOrErr returns the Merchant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantWithdrawRequestEdges) MerchantOrErr() (*Merchant, error) {
	if e.Merchant != nil {
		return e.Merchant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: merchant.Label}
	}
	return nil, &NotLoadedError{edge: "merchant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantWithdrawRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantwithdrawrequest.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case merchantwithdrawrequest.FieldID, merchantwithdrawrequest.FieldMerchantID, merchantwithdrawrequest.FieldAdminID, merchantwithdrawrequest.FieldLedgerID:
			values[i] = new(sql.NullInt64)
		case merchantwithdrawrequest.FieldStatus, merchantwithdrawrequest.FieldPaymentMethod, merchantwithdrawrequest.FieldPaymentAccount, merchantwithdrawrequest.FieldPaymentName, merchantwithdrawrequest.FieldNote, merchantwithdrawrequest.FieldRejectReason:
			values[i] = new(sql.NullString)
		case merchantwithdrawrequest.FieldCreatedAt, merchantwithdrawrequest.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantWithdrawRequest fields.
func (_m *MerchantWithdrawRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantwithdrawrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchantwithdrawrequest.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.Int64
			}
		case merchantwithdrawrequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case merchantwithdrawrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case merchantwithdrawrequest.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case merchantwithdrawrequest.FieldPaymentAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_account", values[i])
			} else if value.Valid {
				_m.PaymentAccount = value.String
			}
		case merchantwithdrawrequest.FieldPaymentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_name", values[i])
			} else if value.Valid {
				_m.PaymentName = value.String
			}
		case merchantwithdrawrequest.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case merchantwithdrawrequest.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = new(int64)
				*_m.AdminID = value.Int64
			}
		case merchantwithdrawrequest.FieldRejectReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reject_reason", values[i])
			} else if value.Valid {
				_m.RejectReason = value.String
			}
		case merchantwithdrawrequest.FieldLedgerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_id", values[i])
			} else if value.Valid {
				_m.LedgerID = new(int64)
				*_m.LedgerID = value.Int64
			}
		case merchantwithdrawrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case merchantwithdrawrequest.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantWithdrawRequest.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantWithdrawRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMerchant queries the "merchant" edge of the MerchantWithdrawRequest entity.
func (_m *MerchantWithdrawRequest) QueryMerchant() *MerchantQuery {
	return NewMerchantWithdrawRequestClient(_m.config).QueryMerchant(_m)
}

// Update returns a builder for updating this MerchantWithdrawRequest.
// Note that you need to call MerchantWithdrawRequest.Unwrap() before calling this method if this MerchantWithdrawRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantWithdrawRequest) Update() *MerchantWithdrawRequestUpdateOne {
	return NewMerchantWithdrawRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantWithdrawRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantWithdrawRequest) Unwrap() *MerchantWithdrawRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantWithdrawRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantWithdrawRequest) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantWithdrawRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MerchantID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("payment_account=")
	builder.WriteString(_m.PaymentAccount)
	builder.WriteString(", ")
	builder.WriteString("payment_name=")
	builder.WriteString(_m.PaymentName)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	if v := _m.AdminID; v != nil {
		builder.WriteString("admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reject_reason=")
	builder.WriteString(_m.RejectReason)
	builder.WriteString(", ")
	if v := _m.LedgerID; v != nil {
		builder.WriteString("ledger_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MerchantWithdrawRequests is a parsable slice of MerchantWithdrawRequest.
type MerchantWithdrawRequests []*MerchantWithdrawRequest
