// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchantdomain"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MerchantDomainDelete is the builder for deleting a MerchantDomain entity.
type MerchantDomainDelete struct {
	config
	hooks    []Hook
	mutation *MerchantDomainMutation
}

// Where appends a list predicates to the MerchantDomainDelete builder.
func (_d *MerchantDomainDelete) Where(ps ...predicate.MerchantDomain) *MerchantDomainDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MerchantDomainDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MerchantDomainDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MerchantDomainDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(merchantdomain.Table, sqlgraph.NewFieldSpec(merchantdomain.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MerchantDomainDeleteOne is the builder for deleting a single MerchantDomain entity.
type MerchantDomainDeleteOne struct {
	_d *MerchantDomainDelete
}

// Where appends a list predicates to the MerchantDomainDelete builder.
func (_d *MerchantDomainDeleteOne) Where(ps ...predicate.MerchantDomain) *MerchantDomainDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MerchantDomainDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantdomain.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MerchantDomainDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
