// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantauditlog"
	"github.com/Wei-Shaw/sub2api/ent/merchantdomain"
	"github.com/Wei-Shaw/sub2api/ent/merchantearningsoutbox"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupcost"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupmarkup"
	"github.com/Wei-Shaw/sub2api/ent/merchantledger"
	"github.com/Wei-Shaw/sub2api/ent/merchantwithdrawrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// MerchantCreate is the builder for creating a Merchant entity.
type MerchantCreate struct {
	config
	mutation *MerchantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MerchantCreate) SetCreatedAt(v time.Time) *MerchantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableCreatedAt(v *time.Time) *MerchantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MerchantCreate) SetUpdatedAt(v time.Time) *MerchantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableUpdatedAt(v *time.Time) *MerchantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MerchantCreate) SetDeletedAt(v time.Time) *MerchantCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableDeletedAt(v *time.Time) *MerchantCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *MerchantCreate) SetOwnerUserID(v int64) *MerchantCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MerchantCreate) SetName(v string) *MerchantCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MerchantCreate) SetStatus(v string) *MerchantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableStatus(v *string) *MerchantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDiscount sets the "discount" field.
func (_c *MerchantCreate) SetDiscount(v float64) *MerchantCreate {
	_c.mutation.SetDiscount(v)
	return _c
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableDiscount(v *float64) *MerchantCreate {
	if v != nil {
		_c.SetDiscount(*v)
	}
	return _c
}

// SetUserMarkupDefault sets the "user_markup_default" field.
func (_c *MerchantCreate) SetUserMarkupDefault(v float64) *MerchantCreate {
	_c.mutation.SetUserMarkupDefault(v)
	return _c
}

// SetNillableUserMarkupDefault sets the "user_markup_default" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableUserMarkupDefault(v *float64) *MerchantCreate {
	if v != nil {
		_c.SetUserMarkupDefault(*v)
	}
	return _c
}

// SetOwnerBalanceBaseline sets the "owner_balance_baseline" field.
func (_c *MerchantCreate) SetOwnerBalanceBaseline(v float64) *MerchantCreate {
	_c.mutation.SetOwnerBalanceBaseline(v)
	return _c
}

// SetNillableOwnerBalanceBaseline sets the "owner_balance_baseline" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableOwnerBalanceBaseline(v *float64) *MerchantCreate {
	if v != nil {
		_c.SetOwnerBalanceBaseline(*v)
	}
	return _c
}

// SetLowBalanceThreshold sets the "low_balance_threshold" field.
func (_c *MerchantCreate) SetLowBalanceThreshold(v float64) *MerchantCreate {
	_c.mutation.SetLowBalanceThreshold(v)
	return _c
}

// SetNillableLowBalanceThreshold sets the "low_balance_threshold" field if the given value is not nil.
func (_c *MerchantCreate) SetNillableLowBalanceThreshold(v *float64) *MerchantCreate {
	if v != nil {
		_c.SetLowBalanceThreshold(*v)
	}
	return _c
}

// SetNotifyEmails sets the "notify_emails" field.
func (_c *MerchantCreate) SetNotifyEmails(v []string) *MerchantCreate {
	_c.mutation.SetNotifyEmails(v)
	return _c
}

// AddDomainIDs adds the "domains" edge to the MerchantDomain entity by IDs.
func (_c *MerchantCreate) AddDomainIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddDomainIDs(ids...)
	return _c
}

// AddDomains adds the "domains" edges to the MerchantDomain entity.
func (_c *MerchantCreate) AddDomains(v ...*MerchantDomain) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomainIDs(ids...)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the MerchantLedger entity by IDs.
func (_c *MerchantCreate) AddLedgerEntryIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddLedgerEntryIDs(ids...)
	return _c
}

// AddLedgerEntries adds the "ledger_entries" edges to the MerchantLedger entity.
func (_c *MerchantCreate) AddLedgerEntries(v ...*MerchantLedger) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLedgerEntryIDs(ids...)
}

// AddOutboxEntryIDs adds the "outbox_entries" edge to the MerchantEarningsOutbox entity by IDs.
func (_c *MerchantCreate) AddOutboxEntryIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddOutboxEntryIDs(ids...)
	return _c
}

// AddOutboxEntries adds the "outbox_entries" edges to the MerchantEarningsOutbox entity.
func (_c *MerchantCreate) AddOutboxEntries(v ...*MerchantEarningsOutbox) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutboxEntryIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the MerchantAuditLog entity by IDs.
func (_c *MerchantCreate) AddAuditLogIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the MerchantAuditLog entity.
func (_c *MerchantCreate) AddAuditLogs(v ...*MerchantAuditLog) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// AddGroupMarkupIDs adds the "group_markups" edge to the MerchantGroupMarkup entity by IDs.
func (_c *MerchantCreate) AddGroupMarkupIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddGroupMarkupIDs(ids...)
	return _c
}

// AddGroupMarkups adds the "group_markups" edges to the MerchantGroupMarkup entity.
func (_c *MerchantCreate) AddGroupMarkups(v ...*MerchantGroupMarkup) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupMarkupIDs(ids...)
}

// AddGroupCostIDs adds the "group_costs" edge to the MerchantGroupCost entity by IDs.
func (_c *MerchantCreate) AddGroupCostIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddGroupCostIDs(ids...)
	return _c
}

// AddGroupCosts adds the "group_costs" edges to the MerchantGroupCost entity.
func (_c *MerchantCreate) AddGroupCosts(v ...*MerchantGroupCost) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupCostIDs(ids...)
}

// AddWithdrawRequestIDs adds the "withdraw_requests" edge to the MerchantWithdrawRequest entity by IDs.
func (_c *MerchantCreate) AddWithdrawRequestIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddWithdrawRequestIDs(ids...)
	return _c
}

// AddWithdrawRequests adds the "withdraw_requests" edges to the MerchantWithdrawRequest entity.
func (_c *MerchantCreate) AddWithdrawRequests(v ...*MerchantWithdrawRequest) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWithdrawRequestIDs(ids...)
}

// AddSubUserIDs adds the "sub_users" edge to the User entity by IDs.
func (_c *MerchantCreate) AddSubUserIDs(ids ...int64) *MerchantCreate {
	_c.mutation.AddSubUserIDs(ids...)
	return _c
}

// AddSubUsers adds the "sub_users" edges to the User entity.
func (_c *MerchantCreate) AddSubUsers(v ...*User) *MerchantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubUserIDs(ids...)
}

// Mutation returns the MerchantMutation object of the builder.
func (_c *MerchantCreate) Mutation() *MerchantMutation {
	return _c.mutation
}

// Save creates the Merchant in the database.
func (_c *MerchantCreate) Save(ctx context.Context) (*Merchant, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MerchantCreate) SaveX(ctx context.Context) *Merchant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MerchantCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if merchant.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized merchant.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := merchant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if merchant.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized merchant.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := merchant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := merchant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Discount(); !ok {
		v := merchant.DefaultDiscount
		_c.mutation.SetDiscount(v)
	}
	if _, ok := _c.mutation.UserMarkupDefault(); !ok {
		v := merchant.DefaultUserMarkupDefault
		_c.mutation.SetUserMarkupDefault(v)
	}
	if _, ok := _c.mutation.OwnerBalanceBaseline(); !ok {
		v := merchant.DefaultOwnerBalanceBaseline
		_c.mutation.SetOwnerBalanceBaseline(v)
	}
	if _, ok := _c.mutation.LowBalanceThreshold(); !ok {
		v := merchant.DefaultLowBalanceThreshold
		_c.mutation.SetLowBalanceThreshold(v)
	}
	if _, ok := _c.mutation.NotifyEmails(); !ok {
		v := merchant.DefaultNotifyEmails
		_c.mutation.SetNotifyEmails(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MerchantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Merchant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Merchant.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Merchant.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Merchant.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := merchant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Merchant.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Merchant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := merchant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Merchant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Discount(); !ok {
		return &ValidationError{Name: "discount", err: errors.New(`ent: missing required field "Merchant.discount"`)}
	}
	if _, ok := _c.mutation.UserMarkupDefault(); !ok {
		return &ValidationError{Name: "user_markup_default", err: errors.New(`ent: missing required field "Merchant.user_markup_default"`)}
	}
	if _, ok := _c.mutation.OwnerBalanceBaseline(); !ok {
		return &ValidationError{Name: "owner_balance_baseline", err: errors.New(`ent: missing required field "Merchant.owner_balance_baseline"`)}
	}
	if _, ok := _c.mutation.LowBalanceThreshold(); !ok {
		return &ValidationError{Name: "low_balance_threshold", err: errors.New(`ent: missing required field "Merchant.low_balance_threshold"`)}
	}
	if _, ok := _c.mutation.NotifyEmails(); !ok {
		return &ValidationError{Name: "notify_emails", err: errors.New(`ent: missing required field "Merchant.notify_emails"`)}
	}
	return nil
}

func (_c *MerchantCreate) sqlSave(ctx context.Context) (*Merchant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MerchantCreate) createSpec() (*Merchant, *sqlgraph.CreateSpec) {
	var (
		_node = &Merchant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(merchant.Table, sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(merchant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(merchant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(merchant.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(merchant.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(merchant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(merchant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Discount(); ok {
		_spec.SetField(merchant.FieldDiscount, field.TypeFloat64, value)
		_node.Discount = value
	}
	if value, ok := _c.mutation.UserMarkupDefault(); ok {
		_spec.SetField(merchant.FieldUserMarkupDefault, field.TypeFloat64, value)
		_node.UserMarkupDefault = value
	}
	if value, ok := _c.mutation.OwnerBalanceBaseline(); ok {
		_spec.SetField(merchant.FieldOwnerBalanceBaseline, field.TypeFloat64, value)
		_node.OwnerBalanceBaseline = value
	}
	if value, ok := _c.mutation.LowBalanceThreshold(); ok {
		_spec.SetField(merchant.FieldLowBalanceThreshold, field.TypeFloat64, value)
		_node.LowBalanceThreshold = value
	}
	if value, ok := _c.mutation.NotifyEmails(); ok {
		_spec.SetField(merchant.FieldNotifyEmails, field.TypeJSON, value)
		_node.NotifyEmails = value
	}
	if nodes := _c.mutation.DomainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.DomainsTable,
			Columns: []string{merchant.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantdomain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.LedgerEntriesTable,
			Columns: []string{merchant.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OutboxEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.OutboxEntriesTable,
			Columns: []string{merchant.OutboxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantearningsoutbox.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.AuditLogsTable,
			Columns: []string{merchant.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupMarkupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.GroupMarkupsTable,
			Columns: []string{merchant.GroupMarkupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantgroupmarkup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupCostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.GroupCostsTable,
			Columns: []string{merchant.GroupCostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantgroupcost.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WithdrawRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.WithdrawRequestsTable,
			Columns: []string{merchant.WithdrawRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchantwithdrawrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   merchant.SubUsersTable,
			Columns: []string{merchant.SubUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Merchant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantCreate) OnConflict(opts ...sql.ConflictOption) *MerchantUpsertOne {
	_c.conflict = opts
	return &MerchantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Merchant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantCreate) OnConflictColumns(columns ...string) *MerchantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantUpsertOne{
		create: _c,
	}
}

type (
	// MerchantUpsertOne is the builder for "upsert"-ing
	//  one Merchant node.
	MerchantUpsertOne struct {
		create *MerchantCreate
	}

	// MerchantUpsert is the "OnConflict" setter.
	MerchantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantUpsert) SetUpdatedAt(v time.Time) *MerchantUpsert {
	u.Set(merchant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateUpdatedAt() *MerchantUpsert {
	u.SetExcluded(merchant.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MerchantUpsert) SetDeletedAt(v time.Time) *MerchantUpsert {
	u.Set(merchant.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateDeletedAt() *MerchantUpsert {
	u.SetExcluded(merchant.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MerchantUpsert) ClearDeletedAt() *MerchantUpsert {
	u.SetNull(merchant.FieldDeletedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *MerchantUpsert) SetOwnerUserID(v int64) *MerchantUpsert {
	u.Set(merchant.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateOwnerUserID() *MerchantUpsert {
	u.SetExcluded(merchant.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *MerchantUpsert) AddOwnerUserID(v int64) *MerchantUpsert {
	u.Add(merchant.FieldOwnerUserID, v)
	return u
}

// SetName sets the "name" field.
func (u *MerchantUpsert) SetName(v string) *MerchantUpsert {
	u.Set(merchant.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateName() *MerchantUpsert {
	u.SetExcluded(merchant.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *MerchantUpsert) SetStatus(v string) *MerchantUpsert {
	u.Set(merchant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateStatus() *MerchantUpsert {
	u.SetExcluded(merchant.FieldStatus)
	return u
}

// SetDiscount sets the "discount" field.
func (u *MerchantUpsert) SetDiscount(v float64) *MerchantUpsert {
	u.Set(merchant.FieldDiscount, v)
	return u
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateDiscount() *MerchantUpsert {
	u.SetExcluded(merchant.FieldDiscount)
	return u
}

// AddDiscount adds v to the "discount" field.
func (u *MerchantUpsert) AddDiscount(v float64) *MerchantUpsert {
	u.Add(merchant.FieldDiscount, v)
	return u
}

// SetUserMarkupDefault sets the "user_markup_default" field.
func (u *MerchantUpsert) SetUserMarkupDefault(v float64) *MerchantUpsert {
	u.Set(merchant.FieldUserMarkupDefault, v)
	return u
}

// UpdateUserMarkupDefault sets the "user_markup_default" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateUserMarkupDefault() *MerchantUpsert {
	u.SetExcluded(merchant.FieldUserMarkupDefault)
	return u
}

// AddUserMarkupDefault adds v to the "user_markup_default" field.
func (u *MerchantUpsert) AddUserMarkupDefault(v float64) *MerchantUpsert {
	u.Add(merchant.FieldUserMarkupDefault, v)
	return u
}

// SetOwnerBalanceBaseline sets the "owner_balance_baseline" field.
func (u *MerchantUpsert) SetOwnerBalanceBaseline(v float64) *MerchantUpsert {
	u.Set(merchant.FieldOwnerBalanceBaseline, v)
	return u
}

// UpdateOwnerBalanceBaseline sets the "owner_balance_baseline" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateOwnerBalanceBaseline() *MerchantUpsert {
	u.SetExcluded(merchant.FieldOwnerBalanceBaseline)
	return u
}

// AddOwnerBalanceBaseline adds v to the "owner_balance_baseline" field.
func (u *MerchantUpsert) AddOwnerBalanceBaseline(v float64) *MerchantUpsert {
	u.Add(merchant.FieldOwnerBalanceBaseline, v)
	return u
}

// SetLowBalanceThreshold sets the "low_balance_threshold" field.
func (u *MerchantUpsert) SetLowBalanceThreshold(v float64) *MerchantUpsert {
	u.Set(merchant.FieldLowBalanceThreshold, v)
	return u
}

// UpdateLowBalanceThreshold sets the "low_balance_threshold" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateLowBalanceThreshold() *MerchantUpsert {
	u.SetExcluded(merchant.FieldLowBalanceThreshold)
	return u
}

// AddLowBalanceThreshold adds v to the "low_balance_threshold" field.
func (u *MerchantUpsert) AddLowBalanceThreshold(v float64) *MerchantUpsert {
	u.Add(merchant.FieldLowBalanceThreshold, v)
	return u
}

// SetNotifyEmails sets the "notify_emails" field.
func (u *MerchantUpsert) SetNotifyEmails(v []string) *MerchantUpsert {
	u.Set(merchant.FieldNotifyEmails, v)
	return u
}

// UpdateNotifyEmails sets the "notify_emails" field to the value that was provided on create.
func (u *MerchantUpsert) UpdateNotifyEmails() *MerchantUpsert {
	u.SetExcluded(merchant.FieldNotifyEmails)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Merchant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantUpsertOne) UpdateNewValues() *MerchantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(merchant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Merchant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MerchantUpsertOne) Ignore() *MerchantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantUpsertOne) DoNothing() *MerchantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantCreate.OnConflict
// documentation for more info.
func (u *MerchantUpsertOne) Update(set func(*MerchantUpsert)) *MerchantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantUpsertOne) SetUpdatedAt(v time.Time) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateUpdatedAt() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MerchantUpsertOne) SetDeletedAt(v time.Time) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateDeletedAt() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MerchantUpsertOne) ClearDeletedAt() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *MerchantUpsertOne) SetOwnerUserID(v int64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *MerchantUpsertOne) AddOwnerUserID(v int64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateOwnerUserID() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *MerchantUpsertOne) SetName(v string) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateName() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantUpsertOne) SetStatus(v string) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateStatus() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateStatus()
	})
}

// SetDiscount sets the "discount" field.
func (u *MerchantUpsertOne) SetDiscount(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *MerchantUpsertOne) AddDiscount(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateDiscount() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateDiscount()
	})
}

// SetUserMarkupDefault sets the "user_markup_default" field.
func (u *MerchantUpsertOne) SetUserMarkupDefault(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetUserMarkupDefault(v)
	})
}

// AddUserMarkupDefault adds v to the "user_markup_default" field.
func (u *MerchantUpsertOne) AddUserMarkupDefault(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.AddUserMarkupDefault(v)
	})
}

// UpdateUserMarkupDefault sets the "user_markup_default" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateUserMarkupDefault() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateUserMarkupDefault()
	})
}

// SetOwnerBalanceBaseline sets the "owner_balance_baseline" field.
func (u *MerchantUpsertOne) SetOwnerBalanceBaseline(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetOwnerBalanceBaseline(v)
	})
}

// AddOwnerBalanceBaseline adds v to the "owner_balance_baseline" field.
func (u *MerchantUpsertOne) AddOwnerBalanceBaseline(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.AddOwnerBalanceBaseline(v)
	})
}

// UpdateOwnerBalanceBaseline sets the "owner_balance_baseline" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateOwnerBalanceBaseline() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateOwnerBalanceBaseline()
	})
}

// SetLowBalanceThreshold sets the "low_balance_threshold" field.
func (u *MerchantUpsertOne) SetLowBalanceThreshold(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetLowBalanceThreshold(v)
	})
}

// AddLowBalanceThreshold adds v to the "low_balance_threshold" field.
func (u *MerchantUpsertOne) AddLowBalanceThreshold(v float64) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.AddLowBalanceThreshold(v)
	})
}

// UpdateLowBalanceThreshold sets the "low_balance_threshold" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateLowBalanceThreshold() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateLowBalanceThreshold()
	})
}

// SetNotifyEmails sets the "notify_emails" field.
func (u *MerchantUpsertOne) SetNotifyEmails(v []string) *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.SetNotifyEmails(v)
	})
}

// UpdateNotifyEmails sets the "notify_emails" field to the value that was provided on create.
func (u *MerchantUpsertOne) UpdateNotifyEmails() *MerchantUpsertOne {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateNotifyEmails()
	})
}

// Exec executes the query.
func (u *MerchantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MerchantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MerchantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MerchantCreateBulk is the builder for creating many Merchant entities in bulk.
type MerchantCreateBulk struct {
	config
	err      error
	builders []*MerchantCreate
	conflict []sql.ConflictOption
}

// Save creates the Merchant entities in the database.
func (_c *MerchantCreateBulk) Save(ctx context.Context) ([]*Merchant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Merchant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MerchantCreateBulk) SaveX(ctx context.Context) []*Merchant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Merchant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantCreateBulk) OnConflict(opts ...sql.ConflictOption) *MerchantUpsertBulk {
	_c.conflict = opts
	return &MerchantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Merchant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantCreateBulk) OnConflictColumns(columns ...string) *MerchantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantUpsertBulk{
		create: _c,
	}
}

// MerchantUpsertBulk is the builder for "upsert"-ing
// a bulk of Merchant nodes.
type MerchantUpsertBulk struct {
	create *MerchantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Merchant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantUpsertBulk) UpdateNewValues() *MerchantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(merchant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Merchant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MerchantUpsertBulk) Ignore() *MerchantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantUpsertBulk) DoNothing() *MerchantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantCreateBulk.OnConflict
// documentation for more info.
func (u *MerchantUpsertBulk) Update(set func(*MerchantUpsert)) *MerchantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantUpsertBulk) SetUpdatedAt(v time.Time) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateUpdatedAt() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MerchantUpsertBulk) SetDeletedAt(v time.Time) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateDeletedAt() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MerchantUpsertBulk) ClearDeletedAt() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *MerchantUpsertBulk) SetOwnerUserID(v int64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *MerchantUpsertBulk) AddOwnerUserID(v int64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateOwnerUserID() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *MerchantUpsertBulk) SetName(v string) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateName() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantUpsertBulk) SetStatus(v string) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateStatus() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateStatus()
	})
}

// SetDiscount sets the "discount" field.
func (u *MerchantUpsertBulk) SetDiscount(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *MerchantUpsertBulk) AddDiscount(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateDiscount() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateDiscount()
	})
}

// SetUserMarkupDefault sets the "user_markup_default" field.
func (u *MerchantUpsertBulk) SetUserMarkupDefault(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetUserMarkupDefault(v)
	})
}

// AddUserMarkupDefault adds v to the "user_markup_default" field.
func (u *MerchantUpsertBulk) AddUserMarkupDefault(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.AddUserMarkupDefault(v)
	})
}

// UpdateUserMarkupDefault sets the "user_markup_default" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateUserMarkupDefault() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateUserMarkupDefault()
	})
}

// SetOwnerBalanceBaseline sets the "owner_balance_baseline" field.
func (u *MerchantUpsertBulk) SetOwnerBalanceBaseline(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetOwnerBalanceBaseline(v)
	})
}

// AddOwnerBalanceBaseline adds v to the "owner_balance_baseline" field.
func (u *MerchantUpsertBulk) AddOwnerBalanceBaseline(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.AddOwnerBalanceBaseline(v)
	})
}

// UpdateOwnerBalanceBaseline sets the "owner_balance_baseline" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateOwnerBalanceBaseline() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateOwnerBalanceBaseline()
	})
}

// SetLowBalanceThreshold sets the "low_balance_threshold" field.
func (u *MerchantUpsertBulk) SetLowBalanceThreshold(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetLowBalanceThreshold(v)
	})
}

// AddLowBalanceThreshold adds v to the "low_balance_threshold" field.
func (u *MerchantUpsertBulk) AddLowBalanceThreshold(v float64) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.AddLowBalanceThreshold(v)
	})
}

// UpdateLowBalanceThreshold sets the "low_balance_threshold" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateLowBalanceThreshold() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateLowBalanceThreshold()
	})
}

// SetNotifyEmails sets the "notify_emails" field.
func (u *MerchantUpsertBulk) SetNotifyEmails(v []string) *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.SetNotifyEmails(v)
	})
}

// UpdateNotifyEmails sets the "notify_emails" field to the value that was provided on create.
func (u *MerchantUpsertBulk) UpdateNotifyEmails() *MerchantUpsertBulk {
	return u.Update(func(s *MerchantUpsert) {
		s.UpdateNotifyEmails()
	})
}

// Exec executes the query.
func (u *MerchantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MerchantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
