// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantwithdrawrequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MerchantWithdrawRequestQuery is the builder for querying MerchantWithdrawRequest entities.
type MerchantWithdrawRequestQuery struct {
	config
	ctx          *QueryContext
	order        []merchantwithdrawrequest.OrderOption
	inters       []Interceptor
	predicates   []predicate.MerchantWithdrawRequest
	withMerchant *MerchantQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MerchantWithdrawRequestQuery builder.
func (_q *MerchantWithdrawRequestQuery) Where(ps ...predicate.MerchantWithdrawRequest) *MerchantWithdrawRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MerchantWithdrawRequestQuery) Limit(limit int) *MerchantWithdrawRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MerchantWithdrawRequestQuery) Offset(offset int) *MerchantWithdrawRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MerchantWithdrawRequestQuery) Unique(unique bool) *MerchantWithdrawRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MerchantWithdrawRequestQuery) Order(o ...merchantwithdrawrequest.OrderOption) *MerchantWithdrawRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMerchant chains the current query on the "merchant" edge.
func (_q *MerchantWithdrawRequestQuery) QueryMerchant() *MerchantQuery {
	query := (&MerchantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchantwithdrawrequest.Table, merchantwithdrawrequest.FieldID, selector),
			sqlgraph.To(merchant.Table, merchant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, merchantwithdrawrequest.MerchantTable, merchantwithdrawrequest.MerchantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MerchantWithdrawRequest entity from the query.
// Returns a *NotFoundError when no MerchantWithdrawRequest was found.
func (_q *MerchantWithdrawRequestQuery) First(ctx context.Context) (*MerchantWithdrawRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{merchantwithdrawrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) FirstX(ctx context.Context) *MerchantWithdrawRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MerchantWithdrawRequest ID from the query.
// Returns a *NotFoundError when no MerchantWithdrawRequest ID was found.
func (_q *MerchantWithdrawRequestQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{merchantwithdrawrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MerchantWithdrawRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MerchantWithdrawRequest entity is found.
// Returns a *NotFoundError when no MerchantWithdrawRequest entities are found.
func (_q *MerchantWithdrawRequestQuery) Only(ctx context.Context) (*MerchantWithdrawRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{merchantwithdrawrequest.Label}
	default:
		return nil, &NotSingularError{merchantwithdrawrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) OnlyX(ctx context.Context) *MerchantWithdrawRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MerchantWithdrawRequest ID in the query.
// Returns a *NotSingularError when more than one MerchantWithdrawRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MerchantWithdrawRequestQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{merchantwithdrawrequest.Label}
	default:
		err = &NotSingularError{merchantwithdrawrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MerchantWithdrawRequests.
func (_q *MerchantWithdrawRequestQuery) All(ctx context.Context) ([]*MerchantWithdrawRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MerchantWithdrawRequest, *MerchantWithdrawRequestQuery]()
	return withInterceptors[[]*MerchantWithdrawRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) AllX(ctx context.Context) []*MerchantWithdrawRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MerchantWithdrawRequest IDs.
func (_q *MerchantWithdrawRequestQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(merchantwithdrawrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MerchantWithdrawRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MerchantWithdrawRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MerchantWithdrawRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MerchantWithdrawRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MerchantWithdrawRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MerchantWithdrawRequestQuery) Clone() *MerchantWithdrawRequestQuery {
	if _q == nil {
		return nil
	}
	return &MerchantWithdrawRequestQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]merchantwithdrawrequest.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.MerchantWithdrawRequest{}, _q.predicates...),
		withMerchant: _q.withMerchant.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMerchant tells the query-builder to eager-load the nodes that are connected to
// the "merchant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantWithdrawRequestQuery) WithMerchant(opts ...func(*MerchantQuery)) *MerchantWithdrawRequestQuery {
	query := (&MerchantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMerchant = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MerchantID int64 `json:"merchant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MerchantWithdrawRequest.Query().
//		GroupBy(merchantwithdrawrequest.FieldMerchantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MerchantWithdrawRequestQuery) GroupBy(field string, fields ...string) *MerchantWithdrawRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MerchantWithdrawRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = merchantwithdrawrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MerchantID int64 `json:"merchant_id,omitempty"`
//	}
//
//	client.MerchantWithdrawRequest.Query().
//		Select(merchantwithdrawrequest.FieldMerchantID).
//		Scan(ctx, &v)
func (_q *MerchantWithdrawRequestQuery) Select(fields ...string) *MerchantWithdrawRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MerchantWithdrawRequestSelect{MerchantWithdrawRequestQuery: _q}
	sbuild.label = merchantwithdrawrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MerchantWithdrawRequestSelect configured with the given aggregations.
func (_q *MerchantWithdrawRequestQuery) Aggregate(fns ...AggregateFunc) *MerchantWithdrawRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MerchantWithdrawRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !merchantwithdrawrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MerchantWithdrawRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MerchantWithdrawRequest, error) {
	var (
		nodes       = []*MerchantWithdrawRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withMerchant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MerchantWithdrawRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MerchantWithdrawRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMerchant; query != nil {
		if err := _q.loadMerchant(ctx, query, nodes, nil,
			func(n *MerchantWithdrawRequest, e *Merchant) { n.Edges.Merchant = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MerchantWithdrawRequestQuery) loadMerchant(ctx context.Context, query *MerchantQuery, nodes []*MerchantWithdrawRequest, init func(*MerchantWithdrawRequest), assign func(*MerchantWithdrawRequest, *Merchant)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MerchantWithdrawRequest)
	for i := range nodes {
		fk := nodes[i].MerchantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(merchant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "merchant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MerchantWithdrawRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MerchantWithdrawRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(merchantwithdrawrequest.Table, merchantwithdrawrequest.Columns, sqlgraph.NewFieldSpec(merchantwithdrawrequest.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchantwithdrawrequest.FieldID)
		for i := range fields {
			if fields[i] != merchantwithdrawrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMerchant != nil {
			_spec.Node.AddColumnOnce(merchantwithdrawrequest.FieldMerchantID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MerchantWithdrawRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(merchantwithdrawrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = merchantwithdrawrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *MerchantWithdrawRequestQuery) ForUpdate(opts ...sql.LockOption) *MerchantWithdrawRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *MerchantWithdrawRequestQuery) ForShare(opts ...sql.LockOption) *MerchantWithdrawRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// MerchantWithdrawRequestGroupBy is the group-by builder for MerchantWithdrawRequest entities.
type MerchantWithdrawRequestGroupBy struct {
	selector
	build *MerchantWithdrawRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MerchantWithdrawRequestGroupBy) Aggregate(fns ...AggregateFunc) *MerchantWithdrawRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MerchantWithdrawRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantWithdrawRequestQuery, *MerchantWithdrawRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MerchantWithdrawRequestGroupBy) sqlScan(ctx context.Context, root *MerchantWithdrawRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MerchantWithdrawRequestSelect is the builder for selecting fields of MerchantWithdrawRequest entities.
type MerchantWithdrawRequestSelect struct {
	*MerchantWithdrawRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MerchantWithdrawRequestSelect) Aggregate(fns ...AggregateFunc) *MerchantWithdrawRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MerchantWithdrawRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantWithdrawRequestQuery, *MerchantWithdrawRequestSelect](ctx, _s.MerchantWithdrawRequestQuery, _s, _s.inters, v)
}

func (_s *MerchantWithdrawRequestSelect) sqlScan(ctx context.Context, root *MerchantWithdrawRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
