// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchantearningsoutbox"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MerchantEarningsOutboxDelete is the builder for deleting a MerchantEarningsOutbox entity.
type MerchantEarningsOutboxDelete struct {
	config
	hooks    []Hook
	mutation *MerchantEarningsOutboxMutation
}

// Where appends a list predicates to the MerchantEarningsOutboxDelete builder.
func (_d *MerchantEarningsOutboxDelete) Where(ps ...predicate.MerchantEarningsOutbox) *MerchantEarningsOutboxDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MerchantEarningsOutboxDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MerchantEarningsOutboxDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MerchantEarningsOutboxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(merchantearningsoutbox.Table, sqlgraph.NewFieldSpec(merchantearningsoutbox.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MerchantEarningsOutboxDeleteOne is the builder for deleting a single MerchantEarningsOutbox entity.
type MerchantEarningsOutboxDeleteOne struct {
	_d *MerchantEarningsOutboxDelete
}

// Where appends a list predicates to the MerchantEarningsOutboxDelete builder.
func (_d *MerchantEarningsOutboxDeleteOne) Where(ps ...predicate.MerchantEarningsOutbox) *MerchantEarningsOutboxDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MerchantEarningsOutboxDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantearningsoutbox.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MerchantEarningsOutboxDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
