// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
)

// Merchant is the model entity for the Merchant schema.
type Merchant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 商户拥有者 user.id；UNIQUE 保证一个 user 最多是一个商户的 owner
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// active / suspended
	Status string `json:"status,omitempty"`
	// 充值环节比例 (0,1]；owner 充池实付 amount × discount，sub_user 充值 owner 得 (1-discount)×amount
	Discount float64 `json:"discount,omitempty"`
	// 消费环节倍率商户级兜底 ≥ 1；分组未配置 markup 时使用
	UserMarkupDefault float64 `json:"user_markup_default,omitempty"`
	// 开通商户时的 owner.balance 快照，对账等式基线
	OwnerBalanceBaseline float64 `json:"owner_balance_baseline,omitempty"`
	// LowBalanceThreshold holds the value of the "low_balance_threshold" field.
	LowBalanceThreshold float64 `json:"low_balance_threshold,omitempty"`
	// NotifyEmails holds the value of the "notify_emails" field.
	NotifyEmails []string `json:"notify_emails,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantQuery when eager-loading is set.
	Edges        MerchantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantEdges holds the relations/edges for other nodes in the graph.
type MerchantEdges struct {
	// Domains holds the value of the domains edge.
	Domains []*MerchantDomain `json:"domains,omitempty"`
	// LedgerEntries holds the value of the ledger_entries edge.
	LedgerEntries []*MerchantLedger `json:"ledger_entries,omitempty"`
	// OutboxEntries holds the value of the outbox_entries edge.
	OutboxEntries []*MerchantEarningsOutbox `json:"outbox_entries,omitempty"`
	// AuditLogs holds the value of the audit_logs edge.
	AuditLogs []*MerchantAuditLog `json:"audit_logs,omitempty"`
	// GroupMarkups holds the value of the group_markups edge.
	GroupMarkups []*MerchantGroupMarkup `json:"group_markups,omitempty"`
	// WithdrawRequests holds the value of the withdraw_requests edge.
	WithdrawRequests []*MerchantWithdrawRequest `json:"withdraw_requests,omitempty"`
	// SubUsers holds the value of the sub_users edge.
	SubUsers []*User `json:"sub_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// DomainsOrErr returns the Domains value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) DomainsOrErr() ([]*MerchantDomain, error) {
	if e.loadedTypes[0] {
		return e.Domains, nil
	}
	return nil, &NotLoadedError{edge: "domains"}
}

// LedgerEntriesOrErr returns the LedgerEntries value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) LedgerEntriesOrErr() ([]*MerchantLedger, error) {
	if e.loadedTypes[1] {
		return e.LedgerEntries, nil
	}
	return nil, &NotLoadedError{edge: "ledger_entries"}
}

// OutboxEntriesOrErr returns the OutboxEntries value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) OutboxEntriesOrErr() ([]*MerchantEarningsOutbox, error) {
	if e.loadedTypes[2] {
		return e.OutboxEntries, nil
	}
	return nil, &NotLoadedError{edge: "outbox_entries"}
}

// AuditLogsOrErr returns the AuditLogs value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) AuditLogsOrErr() ([]*MerchantAuditLog, error) {
	if e.loadedTypes[3] {
		return e.AuditLogs, nil
	}
	return nil, &NotLoadedError{edge: "audit_logs"}
}

// GroupMarkupsOrErr returns the GroupMarkups value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) GroupMarkupsOrErr() ([]*MerchantGroupMarkup, error) {
	if e.loadedTypes[4] {
		return e.GroupMarkups, nil
	}
	return nil, &NotLoadedError{edge: "group_markups"}
}

// WithdrawRequestsOrErr returns the WithdrawRequests value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) WithdrawRequestsOrErr() ([]*MerchantWithdrawRequest, error) {
	if e.loadedTypes[5] {
		return e.WithdrawRequests, nil
	}
	return nil, &NotLoadedError{edge: "withdraw_requests"}
}

// SubUsersOrErr returns the SubUsers value or an error if the edge
// was not loaded in eager-loading.
func (e MerchantEdges) SubUsersOrErr() ([]*User, error) {
	if e.loadedTypes[6] {
		return e.SubUsers, nil
	}
	return nil, &NotLoadedError{edge: "sub_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Merchant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchant.FieldNotifyEmails:
			values[i] = new([]byte)
		case merchant.FieldDiscount, merchant.FieldUserMarkupDefault, merchant.FieldOwnerBalanceBaseline, merchant.FieldLowBalanceThreshold:
			values[i] = new(sql.NullFloat64)
		case merchant.FieldID, merchant.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case merchant.FieldName, merchant.FieldStatus:
			values[i] = new(sql.NullString)
		case merchant.FieldCreatedAt, merchant.FieldUpdatedAt, merchant.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Merchant fields.
func (_m *Merchant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case merchant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case merchant.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case merchant.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case merchant.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case merchant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case merchant.FieldDiscount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount", values[i])
			} else if value.Valid {
				_m.Discount = value.Float64
			}
		case merchant.FieldUserMarkupDefault:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field user_markup_default", values[i])
			} else if value.Valid {
				_m.UserMarkupDefault = value.Float64
			}
		case merchant.FieldOwnerBalanceBaseline:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_balance_baseline", values[i])
			} else if value.Valid {
				_m.OwnerBalanceBaseline = value.Float64
			}
		case merchant.FieldLowBalanceThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field low_balance_threshold", values[i])
			} else if value.Valid {
				_m.LowBalanceThreshold = value.Float64
			}
		case merchant.FieldNotifyEmails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field notify_emails", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NotifyEmails); err != nil {
					return fmt.Errorf("unmarshal field notify_emails: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Merchant.
// This includes values selected through modifiers, order, etc.
func (_m *Merchant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDomains queries the "domains" edge of the Merchant entity.
func (_m *Merchant) QueryDomains() *MerchantDomainQuery {
	return NewMerchantClient(_m.config).QueryDomains(_m)
}

// QueryLedgerEntries queries the "ledger_entries" edge of the Merchant entity.
func (_m *Merchant) QueryLedgerEntries() *MerchantLedgerQuery {
	return NewMerchantClient(_m.config).QueryLedgerEntries(_m)
}

// QueryOutboxEntries queries the "outbox_entries" edge of the Merchant entity.
func (_m *Merchant) QueryOutboxEntries() *MerchantEarningsOutboxQuery {
	return NewMerchantClient(_m.config).QueryOutboxEntries(_m)
}

// QueryAuditLogs queries the "audit_logs" edge of the Merchant entity.
func (_m *Merchant) QueryAuditLogs() *MerchantAuditLogQuery {
	return NewMerchantClient(_m.config).QueryAuditLogs(_m)
}

// QueryGroupMarkups queries the "group_markups" edge of the Merchant entity.
func (_m *Merchant) QueryGroupMarkups() *MerchantGroupMarkupQuery {
	return NewMerchantClient(_m.config).QueryGroupMarkups(_m)
}

// QueryWithdrawRequests queries the "withdraw_requests" edge of the Merchant entity.
func (_m *Merchant) QueryWithdrawRequests() *MerchantWithdrawRequestQuery {
	return NewMerchantClient(_m.config).QueryWithdrawRequests(_m)
}

// QuerySubUsers queries the "sub_users" edge of the Merchant entity.
func (_m *Merchant) QuerySubUsers() *UserQuery {
	return NewMerchantClient(_m.config).QuerySubUsers(_m)
}

// Update returns a builder for updating this Merchant.
// Note that you need to call Merchant.Unwrap() before calling this method if this Merchant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Merchant) Update() *MerchantUpdateOne {
	return NewMerchantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Merchant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Merchant) Unwrap() *Merchant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Merchant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Merchant) String() string {
	var builder strings.Builder
	builder.WriteString("Merchant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("discount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Discount))
	builder.WriteString(", ")
	builder.WriteString("user_markup_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserMarkupDefault))
	builder.WriteString(", ")
	builder.WriteString("owner_balance_baseline=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerBalanceBaseline))
	builder.WriteString(", ")
	builder.WriteString("low_balance_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.LowBalanceThreshold))
	builder.WriteString(", ")
	builder.WriteString("notify_emails=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotifyEmails))
	builder.WriteByte(')')
	return builder.String()
}

// Merchants is a parsable slice of Merchant.
type Merchants []*Merchant
