// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupmarkup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MerchantGroupMarkupUpdate is the builder for updating MerchantGroupMarkup entities.
type MerchantGroupMarkupUpdate struct {
	config
	hooks    []Hook
	mutation *MerchantGroupMarkupMutation
}

// Where appends a list predicates to the MerchantGroupMarkupUpdate builder.
func (_u *MerchantGroupMarkupUpdate) Where(ps ...predicate.MerchantGroupMarkup) *MerchantGroupMarkupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MerchantGroupMarkupUpdate) SetUpdatedAt(v time.Time) *MerchantGroupMarkupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *MerchantGroupMarkupUpdate) SetMerchantID(v int64) *MerchantGroupMarkupUpdate {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdate) SetNillableMerchantID(v *int64) *MerchantGroupMarkupUpdate {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MerchantGroupMarkupUpdate) SetGroupID(v int64) *MerchantGroupMarkupUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdate) SetNillableGroupID(v *int64) *MerchantGroupMarkupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MerchantGroupMarkupUpdate) AddGroupID(v int64) *MerchantGroupMarkupUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSellRate sets the "sell_rate" field.
func (_u *MerchantGroupMarkupUpdate) SetSellRate(v float64) *MerchantGroupMarkupUpdate {
	_u.mutation.ResetSellRate()
	_u.mutation.SetSellRate(v)
	return _u
}

// SetNillableSellRate sets the "sell_rate" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdate) SetNillableSellRate(v *float64) *MerchantGroupMarkupUpdate {
	if v != nil {
		_u.SetSellRate(*v)
	}
	return _u
}

// AddSellRate adds value to the "sell_rate" field.
func (_u *MerchantGroupMarkupUpdate) AddSellRate(v float64) *MerchantGroupMarkupUpdate {
	_u.mutation.AddSellRate(v)
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *MerchantGroupMarkupUpdate) SetMerchant(v *Merchant) *MerchantGroupMarkupUpdate {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the MerchantGroupMarkupMutation object of the builder.
func (_u *MerchantGroupMarkupUpdate) Mutation() *MerchantGroupMarkupMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *MerchantGroupMarkupUpdate) ClearMerchant() *MerchantGroupMarkupUpdate {
	_u.mutation.ClearMerchant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MerchantGroupMarkupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MerchantGroupMarkupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MerchantGroupMarkupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MerchantGroupMarkupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MerchantGroupMarkupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := merchantgroupmarkup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MerchantGroupMarkupUpdate) check() error {
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantGroupMarkup.merchant"`)
	}
	return nil
}

func (_u *MerchantGroupMarkupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantgroupmarkup.Table, merchantgroupmarkup.Columns, sqlgraph.NewFieldSpec(merchantgroupmarkup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantgroupmarkup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(merchantgroupmarkup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(merchantgroupmarkup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SellRate(); ok {
		_spec.SetField(merchantgroupmarkup.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellRate(); ok {
		_spec.AddField(merchantgroupmarkup.FieldSellRate, field.TypeFloat64, value)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantgroupmarkup.MerchantTable,
			Columns: []string{merchantgroupmarkup.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantgroupmarkup.MerchantTable,
			Columns: []string{merchantgroupmarkup.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantgroupmarkup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MerchantGroupMarkupUpdateOne is the builder for updating a single MerchantGroupMarkup entity.
type MerchantGroupMarkupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MerchantGroupMarkupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MerchantGroupMarkupUpdateOne) SetUpdatedAt(v time.Time) *MerchantGroupMarkupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *MerchantGroupMarkupUpdateOne) SetMerchantID(v int64) *MerchantGroupMarkupUpdateOne {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdateOne) SetNillableMerchantID(v *int64) *MerchantGroupMarkupUpdateOne {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MerchantGroupMarkupUpdateOne) SetGroupID(v int64) *MerchantGroupMarkupUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdateOne) SetNillableGroupID(v *int64) *MerchantGroupMarkupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MerchantGroupMarkupUpdateOne) AddGroupID(v int64) *MerchantGroupMarkupUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSellRate sets the "sell_rate" field.
func (_u *MerchantGroupMarkupUpdateOne) SetSellRate(v float64) *MerchantGroupMarkupUpdateOne {
	_u.mutation.ResetSellRate()
	_u.mutation.SetSellRate(v)
	return _u
}

// SetNillableSellRate sets the "sell_rate" field if the given value is not nil.
func (_u *MerchantGroupMarkupUpdateOne) SetNillableSellRate(v *float64) *MerchantGroupMarkupUpdateOne {
	if v != nil {
		_u.SetSellRate(*v)
	}
	return _u
}

// AddSellRate adds value to the "sell_rate" field.
func (_u *MerchantGroupMarkupUpdateOne) AddSellRate(v float64) *MerchantGroupMarkupUpdateOne {
	_u.mutation.AddSellRate(v)
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *MerchantGroupMarkupUpdateOne) SetMerchant(v *Merchant) *MerchantGroupMarkupUpdateOne {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the MerchantGroupMarkupMutation object of the builder.
func (_u *MerchantGroupMarkupUpdateOne) Mutation() *MerchantGroupMarkupMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *MerchantGroupMarkupUpdateOne) ClearMerchant() *MerchantGroupMarkupUpdateOne {
	_u.mutation.ClearMerchant()
	return _u
}

// Where appends a list predicates to the MerchantGroupMarkupUpdate builder.
func (_u *MerchantGroupMarkupUpdateOne) Where(ps ...predicate.MerchantGroupMarkup) *MerchantGroupMarkupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MerchantGroupMarkupUpdateOne) Select(field string, fields ...string) *MerchantGroupMarkupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MerchantGroupMarkup entity.
func (_u *MerchantGroupMarkupUpdateOne) Save(ctx context.Context) (*MerchantGroupMarkup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MerchantGroupMarkupUpdateOne) SaveX(ctx context.Context) *MerchantGroupMarkup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MerchantGroupMarkupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MerchantGroupMarkupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MerchantGroupMarkupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := merchantgroupmarkup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MerchantGroupMarkupUpdateOne) check() error {
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantGroupMarkup.merchant"`)
	}
	return nil
}

func (_u *MerchantGroupMarkupUpdateOne) sqlSave(ctx context.Context) (_node *MerchantGroupMarkup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantgroupmarkup.Table, merchantgroupmarkup.Columns, sqlgraph.NewFieldSpec(merchantgroupmarkup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MerchantGroupMarkup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchantgroupmarkup.FieldID)
		for _, f := range fields {
			if !merchantgroupmarkup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != merchantgroupmarkup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantgroupmarkup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(merchantgroupmarkup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(merchantgroupmarkup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SellRate(); ok {
		_spec.SetField(merchantgroupmarkup.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellRate(); ok {
		_spec.AddField(merchantgroupmarkup.FieldSellRate, field.TypeFloat64, value)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantgroupmarkup.MerchantTable,
			Columns: []string{merchantgroupmarkup.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantgroupmarkup.MerchantTable,
			Columns: []string{merchantgroupmarkup.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MerchantGroupMarkup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantgroupmarkup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
