// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantwithdrawrequest"
)

// MerchantWithdrawRequestCreate is the builder for creating a MerchantWithdrawRequest entity.
type MerchantWithdrawRequestCreate struct {
	config
	mutation *MerchantWithdrawRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMerchantID sets the "merchant_id" field.
func (_c *MerchantWithdrawRequestCreate) SetMerchantID(v int64) *MerchantWithdrawRequestCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *MerchantWithdrawRequestCreate) SetAmount(v float64) *MerchantWithdrawRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MerchantWithdrawRequestCreate) SetStatus(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableStatus(v *string) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *MerchantWithdrawRequestCreate) SetPaymentMethod(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetPaymentAccount sets the "payment_account" field.
func (_c *MerchantWithdrawRequestCreate) SetPaymentAccount(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetPaymentAccount(v)
	return _c
}

// SetPaymentName sets the "payment_name" field.
func (_c *MerchantWithdrawRequestCreate) SetPaymentName(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetPaymentName(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *MerchantWithdrawRequestCreate) SetNote(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableNote(v *string) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetAdminID sets the "admin_id" field.
func (_c *MerchantWithdrawRequestCreate) SetAdminID(v int64) *MerchantWithdrawRequestCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableAdminID(v *int64) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetAdminID(*v)
	}
	return _c
}

// SetRejectReason sets the "reject_reason" field.
func (_c *MerchantWithdrawRequestCreate) SetRejectReason(v string) *MerchantWithdrawRequestCreate {
	_c.mutation.SetRejectReason(v)
	return _c
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableRejectReason(v *string) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetRejectReason(*v)
	}
	return _c
}

// SetLedgerID sets the "ledger_id" field.
func (_c *MerchantWithdrawRequestCreate) SetLedgerID(v int64) *MerchantWithdrawRequestCreate {
	_c.mutation.SetLedgerID(v)
	return _c
}

// SetNillableLedgerID sets the "ledger_id" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableLedgerID(v *int64) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetLedgerID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MerchantWithdrawRequestCreate) SetCreatedAt(v time.Time) *MerchantWithdrawRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableCreatedAt(v *time.Time) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *MerchantWithdrawRequestCreate) SetProcessedAt(v time.Time) *MerchantWithdrawRequestCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *MerchantWithdrawRequestCreate) SetNillableProcessedAt(v *time.Time) *MerchantWithdrawRequestCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_c *MerchantWithdrawRequestCreate) SetMerchant(v *Merchant) *MerchantWithdrawRequestCreate {
	return _c.SetMerchantID(v.ID)
}

// Mutation returns the MerchantWithdrawRequestMutation object of the builder.
func (_c *MerchantWithdrawRequestCreate) Mutation() *MerchantWithdrawRequestMutation {
	return _c.mutation
}

// Save creates the MerchantWithdrawRequest in the database.
func (_c *MerchantWithdrawRequestCreate) Save(ctx context.Context) (*MerchantWithdrawRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MerchantWithdrawRequestCreate) SaveX(ctx context.Context) *MerchantWithdrawRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantWithdrawRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantWithdrawRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MerchantWithdrawRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := merchantwithdrawrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := merchantwithdrawrequest.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.RejectReason(); !ok {
		v := merchantwithdrawrequest.DefaultRejectReason
		_c.mutation.SetRejectReason(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := merchantwithdrawrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MerchantWithdrawRequestCreate) check() error {
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.merchant_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := merchantwithdrawrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MerchantWithdrawRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.payment_method"`)}
	}
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := merchantwithdrawrequest.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "MerchantWithdrawRequest.payment_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentAccount(); !ok {
		return &ValidationError{Name: "payment_account", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.payment_account"`)}
	}
	if v, ok := _c.mutation.PaymentAccount(); ok {
		if err := merchantwithdrawrequest.PaymentAccountValidator(v); err != nil {
			return &ValidationError{Name: "payment_account", err: fmt.Errorf(`ent: validator failed for field "MerchantWithdrawRequest.payment_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentName(); !ok {
		return &ValidationError{Name: "payment_name", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.payment_name"`)}
	}
	if v, ok := _c.mutation.PaymentName(); ok {
		if err := merchantwithdrawrequest.PaymentNameValidator(v); err != nil {
			return &ValidationError{Name: "payment_name", err: fmt.Errorf(`ent: validator failed for field "MerchantWithdrawRequest.payment_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.note"`)}
	}
	if _, ok := _c.mutation.RejectReason(); !ok {
		return &ValidationError{Name: "reject_reason", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.reject_reason"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MerchantWithdrawRequest.created_at"`)}
	}
	if len(_c.mutation.MerchantIDs()) == 0 {
		return &ValidationError{Name: "merchant", err: errors.New(`ent: missing required edge "MerchantWithdrawRequest.merchant"`)}
	}
	return nil
}

func (_c *MerchantWithdrawRequestCreate) sqlSave(ctx context.Context) (*MerchantWithdrawRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MerchantWithdrawRequestCreate) createSpec() (*MerchantWithdrawRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &MerchantWithdrawRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(merchantwithdrawrequest.Table, sqlgraph.NewFieldSpec(merchantwithdrawrequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.PaymentAccount(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldPaymentAccount, field.TypeString, value)
		_node.PaymentAccount = value
	}
	if value, ok := _c.mutation.PaymentName(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldPaymentName, field.TypeString, value)
		_node.PaymentName = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldAdminID, field.TypeInt64, value)
		_node.AdminID = &value
	}
	if value, ok := _c.mutation.RejectReason(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldRejectReason, field.TypeString, value)
		_node.RejectReason = value
	}
	if value, ok := _c.mutation.LedgerID(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldLedgerID, field.TypeInt64, value)
		_node.LedgerID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(merchantwithdrawrequest.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if nodes := _c.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantwithdrawrequest.MerchantTable,
			Columns: []string{merchantwithdrawrequest.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MerchantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantWithdrawRequest.Create().
//		SetMerchantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantWithdrawRequestUpsert) {
//			SetMerchantID(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantWithdrawRequestCreate) OnConflict(opts ...sql.ConflictOption) *MerchantWithdrawRequestUpsertOne {
	_c.conflict = opts
	return &MerchantWithdrawRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantWithdrawRequestCreate) OnConflictColumns(columns ...string) *MerchantWithdrawRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantWithdrawRequestUpsertOne{
		create: _c,
	}
}

type (
	// MerchantWithdrawRequestUpsertOne is the builder for "upsert"-ing
	//  one MerchantWithdrawRequest node.
	MerchantWithdrawRequestUpsertOne struct {
		create *MerchantWithdrawRequestCreate
	}

	// MerchantWithdrawRequestUpsert is the "OnConflict" setter.
	MerchantWithdrawRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantWithdrawRequestUpsert) SetMerchantID(v int64) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldMerchantID, v)
	return u
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateMerchantID() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldMerchantID)
	return u
}

// SetAmount sets the "amount" field.
func (u *MerchantWithdrawRequestUpsert) SetAmount(v float64) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateAmount() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *MerchantWithdrawRequestUpsert) AddAmount(v float64) *MerchantWithdrawRequestUpsert {
	u.Add(merchantwithdrawrequest.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *MerchantWithdrawRequestUpsert) SetStatus(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateStatus() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldStatus)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *MerchantWithdrawRequestUpsert) SetPaymentMethod(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdatePaymentMethod() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldPaymentMethod)
	return u
}

// SetPaymentAccount sets the "payment_account" field.
func (u *MerchantWithdrawRequestUpsert) SetPaymentAccount(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldPaymentAccount, v)
	return u
}

// UpdatePaymentAccount sets the "payment_account" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdatePaymentAccount() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldPaymentAccount)
	return u
}

// SetPaymentName sets the "payment_name" field.
func (u *MerchantWithdrawRequestUpsert) SetPaymentName(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldPaymentName, v)
	return u
}

// UpdatePaymentName sets the "payment_name" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdatePaymentName() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldPaymentName)
	return u
}

// SetNote sets the "note" field.
func (u *MerchantWithdrawRequestUpsert) SetNote(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateNote() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldNote)
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *MerchantWithdrawRequestUpsert) SetAdminID(v int64) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldAdminID, v)
	return u
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateAdminID() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldAdminID)
	return u
}

// AddAdminID adds v to the "admin_id" field.
func (u *MerchantWithdrawRequestUpsert) AddAdminID(v int64) *MerchantWithdrawRequestUpsert {
	u.Add(merchantwithdrawrequest.FieldAdminID, v)
	return u
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *MerchantWithdrawRequestUpsert) ClearAdminID() *MerchantWithdrawRequestUpsert {
	u.SetNull(merchantwithdrawrequest.FieldAdminID)
	return u
}

// SetRejectReason sets the "reject_reason" field.
func (u *MerchantWithdrawRequestUpsert) SetRejectReason(v string) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldRejectReason, v)
	return u
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateRejectReason() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldRejectReason)
	return u
}

// SetLedgerID sets the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsert) SetLedgerID(v int64) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldLedgerID, v)
	return u
}

// UpdateLedgerID sets the "ledger_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateLedgerID() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldLedgerID)
	return u
}

// AddLedgerID adds v to the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsert) AddLedgerID(v int64) *MerchantWithdrawRequestUpsert {
	u.Add(merchantwithdrawrequest.FieldLedgerID, v)
	return u
}

// ClearLedgerID clears the value of the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsert) ClearLedgerID() *MerchantWithdrawRequestUpsert {
	u.SetNull(merchantwithdrawrequest.FieldLedgerID)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *MerchantWithdrawRequestUpsert) SetProcessedAt(v time.Time) *MerchantWithdrawRequestUpsert {
	u.Set(merchantwithdrawrequest.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsert) UpdateProcessedAt() *MerchantWithdrawRequestUpsert {
	u.SetExcluded(merchantwithdrawrequest.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *MerchantWithdrawRequestUpsert) ClearProcessedAt() *MerchantWithdrawRequestUpsert {
	u.SetNull(merchantwithdrawrequest.FieldProcessedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantWithdrawRequestUpsertOne) UpdateNewValues() *MerchantWithdrawRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(merchantwithdrawrequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MerchantWithdrawRequestUpsertOne) Ignore() *MerchantWithdrawRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantWithdrawRequestUpsertOne) DoNothing() *MerchantWithdrawRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantWithdrawRequestCreate.OnConflict
// documentation for more info.
func (u *MerchantWithdrawRequestUpsertOne) Update(set func(*MerchantWithdrawRequestUpsert)) *MerchantWithdrawRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantWithdrawRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantWithdrawRequestUpsertOne) SetMerchantID(v int64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetMerchantID(v)
	})
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateMerchantID() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateMerchantID()
	})
}

// SetAmount sets the "amount" field.
func (u *MerchantWithdrawRequestUpsertOne) SetAmount(v float64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MerchantWithdrawRequestUpsertOne) AddAmount(v float64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateAmount() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantWithdrawRequestUpsertOne) SetStatus(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateStatus() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *MerchantWithdrawRequestUpsertOne) SetPaymentMethod(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdatePaymentMethod() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentAccount sets the "payment_account" field.
func (u *MerchantWithdrawRequestUpsertOne) SetPaymentAccount(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentAccount(v)
	})
}

// UpdatePaymentAccount sets the "payment_account" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdatePaymentAccount() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentAccount()
	})
}

// SetPaymentName sets the "payment_name" field.
func (u *MerchantWithdrawRequestUpsertOne) SetPaymentName(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentName(v)
	})
}

// UpdatePaymentName sets the "payment_name" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdatePaymentName() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentName()
	})
}

// SetNote sets the "note" field.
func (u *MerchantWithdrawRequestUpsertOne) SetNote(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateNote() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateNote()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertOne) SetAdminID(v int64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertOne) AddAdminID(v int64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateAdminID() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertOne) ClearAdminID() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearAdminID()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *MerchantWithdrawRequestUpsertOne) SetRejectReason(v string) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateRejectReason() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// SetLedgerID sets the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertOne) SetLedgerID(v int64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetLedgerID(v)
	})
}

// AddLedgerID adds v to the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertOne) AddLedgerID(v int64) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddLedgerID(v)
	})
}

// UpdateLedgerID sets the "ledger_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateLedgerID() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateLedgerID()
	})
}

// ClearLedgerID clears the value of the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertOne) ClearLedgerID() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearLedgerID()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *MerchantWithdrawRequestUpsertOne) SetProcessedAt(v time.Time) *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertOne) UpdateProcessedAt() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *MerchantWithdrawRequestUpsertOne) ClearProcessedAt() *MerchantWithdrawRequestUpsertOne {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearProcessedAt()
	})
}

// Exec executes the query.
func (u *MerchantWithdrawRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantWithdrawRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantWithdrawRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MerchantWithdrawRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MerchantWithdrawRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MerchantWithdrawRequestCreateBulk is the builder for creating many MerchantWithdrawRequest entities in bulk.
type MerchantWithdrawRequestCreateBulk struct {
	config
	err      error
	builders []*MerchantWithdrawRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the MerchantWithdrawRequest entities in the database.
func (_c *MerchantWithdrawRequestCreateBulk) Save(ctx context.Context) ([]*MerchantWithdrawRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MerchantWithdrawRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantWithdrawRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MerchantWithdrawRequestCreateBulk) SaveX(ctx context.Context) []*MerchantWithdrawRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantWithdrawRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantWithdrawRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantWithdrawRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantWithdrawRequestUpsert) {
//			SetMerchantID(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantWithdrawRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *MerchantWithdrawRequestUpsertBulk {
	_c.conflict = opts
	return &MerchantWithdrawRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantWithdrawRequestCreateBulk) OnConflictColumns(columns ...string) *MerchantWithdrawRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantWithdrawRequestUpsertBulk{
		create: _c,
	}
}

// MerchantWithdrawRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of MerchantWithdrawRequest nodes.
type MerchantWithdrawRequestUpsertBulk struct {
	create *MerchantWithdrawRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantWithdrawRequestUpsertBulk) UpdateNewValues() *MerchantWithdrawRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(merchantwithdrawrequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantWithdrawRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MerchantWithdrawRequestUpsertBulk) Ignore() *MerchantWithdrawRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantWithdrawRequestUpsertBulk) DoNothing() *MerchantWithdrawRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantWithdrawRequestCreateBulk.OnConflict
// documentation for more info.
func (u *MerchantWithdrawRequestUpsertBulk) Update(set func(*MerchantWithdrawRequestUpsert)) *MerchantWithdrawRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantWithdrawRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetMerchantID(v int64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetMerchantID(v)
	})
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateMerchantID() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateMerchantID()
	})
}

// SetAmount sets the "amount" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetAmount(v float64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *MerchantWithdrawRequestUpsertBulk) AddAmount(v float64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateAmount() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetStatus(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateStatus() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetPaymentMethod(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdatePaymentMethod() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentAccount sets the "payment_account" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetPaymentAccount(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentAccount(v)
	})
}

// UpdatePaymentAccount sets the "payment_account" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdatePaymentAccount() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentAccount()
	})
}

// SetPaymentName sets the "payment_name" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetPaymentName(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetPaymentName(v)
	})
}

// UpdatePaymentName sets the "payment_name" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdatePaymentName() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdatePaymentName()
	})
}

// SetNote sets the "note" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetNote(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateNote() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateNote()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetAdminID(v int64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) AddAdminID(v int64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateAdminID() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) ClearAdminID() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearAdminID()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetRejectReason(v string) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateRejectReason() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// SetLedgerID sets the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetLedgerID(v int64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetLedgerID(v)
	})
}

// AddLedgerID adds v to the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) AddLedgerID(v int64) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.AddLedgerID(v)
	})
}

// UpdateLedgerID sets the "ledger_id" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateLedgerID() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateLedgerID()
	})
}

// ClearLedgerID clears the value of the "ledger_id" field.
func (u *MerchantWithdrawRequestUpsertBulk) ClearLedgerID() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearLedgerID()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *MerchantWithdrawRequestUpsertBulk) SetProcessedAt(v time.Time) *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *MerchantWithdrawRequestUpsertBulk) UpdateProcessedAt() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *MerchantWithdrawRequestUpsertBulk) ClearProcessedAt() *MerchantWithdrawRequestUpsertBulk {
	return u.Update(func(s *MerchantWithdrawRequestUpsert) {
		s.ClearProcessedAt()
	})
}

// Exec executes the query.
func (u *MerchantWithdrawRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MerchantWithdrawRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantWithdrawRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantWithdrawRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
