// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupcost"
)

// MerchantGroupCost is the model entity for the MerchantGroupCost schema.
type MerchantGroupCost struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// 商户在该分组上的拿货价倍率 > 0；终端用户付的钱里平台扣 base × cost_rate
	CostRate float64 `json:"cost_rate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantGroupCostQuery when eager-loading is set.
	Edges        MerchantGroupCostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantGroupCostEdges holds the relations/edges for other nodes in the graph.
type MerchantGroupCostEdges struct {
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MerchantOrErr returns the Merchant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantGroupCostEdges) MerchantOrErr() (*Merchant, error) {
	if e.Merchant != nil {
		return e.Merchant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: merchant.Label}
	}
	return nil, &NotLoadedError{edge: "merchant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantGroupCost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantgroupcost.FieldCostRate:
			values[i] = new(sql.NullFloat64)
		case merchantgroupcost.FieldID, merchantgroupcost.FieldMerchantID, merchantgroupcost.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case merchantgroupcost.FieldCreatedAt, merchantgroupcost.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantGroupCost fields.
func (_m *MerchantGroupCost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantgroupcost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchantgroupcost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case merchantgroupcost.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case merchantgroupcost.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.Int64
			}
		case merchantgroupcost.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case merchantgroupcost.FieldCostRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_rate", values[i])
			} else if value.Valid {
				_m.CostRate = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantGroupCost.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantGroupCost) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMerchant queries the "merchant" edge of the MerchantGroupCost entity.
func (_m *MerchantGroupCost) QueryMerchant() *MerchantQuery {
	return NewMerchantGroupCostClient(_m.config).QueryMerchant(_m)
}

// Update returns a builder for updating this MerchantGroupCost.
// Note that you need to call MerchantGroupCost.Unwrap() before calling this method if this MerchantGroupCost
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantGroupCost) Update() *MerchantGroupCostUpdateOne {
	return NewMerchantGroupCostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantGroupCost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantGroupCost) Unwrap() *MerchantGroupCost {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantGroupCost is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantGroupCost) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantGroupCost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MerchantID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("cost_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostRate))
	builder.WriteByte(')')
	return builder.String()
}

// MerchantGroupCosts is a parsable slice of MerchantGroupCost.
type MerchantGroupCosts []*MerchantGroupCost
