// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantauditlog"
)

// MerchantAuditLog is the model entity for the MerchantAuditLog schema.
type MerchantAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// 操作的 admin（NULL=系统）
	AdminID *int64 `json:"admin_id,omitempty"`
	// discount / user_markup / status / domain_*
	Field string `json:"field,omitempty"`
	// OldValue holds the value of the "old_value" field.
	OldValue *string `json:"old_value,omitempty"`
	// NewValue holds the value of the "new_value" field.
	NewValue *string `json:"new_value,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantAuditLogQuery when eager-loading is set.
	Edges        MerchantAuditLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantAuditLogEdges holds the relations/edges for other nodes in the graph.
type MerchantAuditLogEdges struct {
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MerchantOrErr returns the Merchant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantAuditLogEdges) MerchantOrErr() (*Merchant, error) {
	if e.Merchant != nil {
		return e.Merchant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: merchant.Label}
	}
	return nil, &NotLoadedError{edge: "merchant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantauditlog.FieldID, merchantauditlog.FieldMerchantID, merchantauditlog.FieldAdminID:
			values[i] = new(sql.NullInt64)
		case merchantauditlog.FieldField, merchantauditlog.FieldOldValue, merchantauditlog.FieldNewValue, merchantauditlog.FieldReason:
			values[i] = new(sql.NullString)
		case merchantauditlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantAuditLog fields.
func (_m *MerchantAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchantauditlog.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.Int64
			}
		case merchantauditlog.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = new(int64)
				*_m.AdminID = value.Int64
			}
		case merchantauditlog.FieldField:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field", values[i])
			} else if value.Valid {
				_m.Field = value.String
			}
		case merchantauditlog.FieldOldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_value", values[i])
			} else if value.Valid {
				_m.OldValue = new(string)
				*_m.OldValue = value.String
			}
		case merchantauditlog.FieldNewValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_value", values[i])
			} else if value.Valid {
				_m.NewValue = new(string)
				*_m.NewValue = value.String
			}
		case merchantauditlog.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case merchantauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMerchant queries the "merchant" edge of the MerchantAuditLog entity.
func (_m *MerchantAuditLog) QueryMerchant() *MerchantQuery {
	return NewMerchantAuditLogClient(_m.config).QueryMerchant(_m)
}

// Update returns a builder for updating this MerchantAuditLog.
// Note that you need to call MerchantAuditLog.Unwrap() before calling this method if this MerchantAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantAuditLog) Update() *MerchantAuditLogUpdateOne {
	return NewMerchantAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantAuditLog) Unwrap() *MerchantAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MerchantID))
	builder.WriteString(", ")
	if v := _m.AdminID; v != nil {
		builder.WriteString("admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("field=")
	builder.WriteString(_m.Field)
	builder.WriteString(", ")
	if v := _m.OldValue; v != nil {
		builder.WriteString("old_value=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NewValue; v != nil {
		builder.WriteString("new_value=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MerchantAuditLogs is a parsable slice of MerchantAuditLog.
type MerchantAuditLogs []*MerchantAuditLog
