// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantauditlog"
	"github.com/Wei-Shaw/sub2api/ent/merchantdomain"
	"github.com/Wei-Shaw/sub2api/ent/merchantearningsoutbox"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupmarkup"
	"github.com/Wei-Shaw/sub2api/ent/merchantledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// MerchantQuery is the builder for querying Merchant entities.
type MerchantQuery struct {
	config
	ctx               *QueryContext
	order             []merchant.OrderOption
	inters            []Interceptor
	predicates        []predicate.Merchant
	withDomains       *MerchantDomainQuery
	withLedgerEntries *MerchantLedgerQuery
	withOutboxEntries *MerchantEarningsOutboxQuery
	withAuditLogs     *MerchantAuditLogQuery
	withGroupMarkups  *MerchantGroupMarkupQuery
	withSubUsers      *UserQuery
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MerchantQuery builder.
func (_q *MerchantQuery) Where(ps ...predicate.Merchant) *MerchantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MerchantQuery) Limit(limit int) *MerchantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MerchantQuery) Offset(offset int) *MerchantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MerchantQuery) Unique(unique bool) *MerchantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MerchantQuery) Order(o ...merchant.OrderOption) *MerchantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDomains chains the current query on the "domains" edge.
func (_q *MerchantQuery) QueryDomains() *MerchantDomainQuery {
	query := (&MerchantDomainClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(merchantdomain.Table, merchantdomain.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.DomainsTable, merchant.DomainsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLedgerEntries chains the current query on the "ledger_entries" edge.
func (_q *MerchantQuery) QueryLedgerEntries() *MerchantLedgerQuery {
	query := (&MerchantLedgerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(merchantledger.Table, merchantledger.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.LedgerEntriesTable, merchant.LedgerEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOutboxEntries chains the current query on the "outbox_entries" edge.
func (_q *MerchantQuery) QueryOutboxEntries() *MerchantEarningsOutboxQuery {
	query := (&MerchantEarningsOutboxClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(merchantearningsoutbox.Table, merchantearningsoutbox.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.OutboxEntriesTable, merchant.OutboxEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuditLogs chains the current query on the "audit_logs" edge.
func (_q *MerchantQuery) QueryAuditLogs() *MerchantAuditLogQuery {
	query := (&MerchantAuditLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(merchantauditlog.Table, merchantauditlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.AuditLogsTable, merchant.AuditLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupMarkups chains the current query on the "group_markups" edge.
func (_q *MerchantQuery) QueryGroupMarkups() *MerchantGroupMarkupQuery {
	query := (&MerchantGroupMarkupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(merchantgroupmarkup.Table, merchantgroupmarkup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.GroupMarkupsTable, merchant.GroupMarkupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubUsers chains the current query on the "sub_users" edge.
func (_q *MerchantQuery) QuerySubUsers() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(merchant.Table, merchant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, merchant.SubUsersTable, merchant.SubUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Merchant entity from the query.
// Returns a *NotFoundError when no Merchant was found.
func (_q *MerchantQuery) First(ctx context.Context) (*Merchant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{merchant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MerchantQuery) FirstX(ctx context.Context) *Merchant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Merchant ID from the query.
// Returns a *NotFoundError when no Merchant ID was found.
func (_q *MerchantQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{merchant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MerchantQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Merchant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Merchant entity is found.
// Returns a *NotFoundError when no Merchant entities are found.
func (_q *MerchantQuery) Only(ctx context.Context) (*Merchant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{merchant.Label}
	default:
		return nil, &NotSingularError{merchant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MerchantQuery) OnlyX(ctx context.Context) *Merchant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Merchant ID in the query.
// Returns a *NotSingularError when more than one Merchant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MerchantQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{merchant.Label}
	default:
		err = &NotSingularError{merchant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MerchantQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Merchants.
func (_q *MerchantQuery) All(ctx context.Context) ([]*Merchant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Merchant, *MerchantQuery]()
	return withInterceptors[[]*Merchant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MerchantQuery) AllX(ctx context.Context) []*Merchant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Merchant IDs.
func (_q *MerchantQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(merchant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MerchantQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MerchantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MerchantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MerchantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MerchantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MerchantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MerchantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MerchantQuery) Clone() *MerchantQuery {
	if _q == nil {
		return nil
	}
	return &MerchantQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]merchant.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.Merchant{}, _q.predicates...),
		withDomains:       _q.withDomains.Clone(),
		withLedgerEntries: _q.withLedgerEntries.Clone(),
		withOutboxEntries: _q.withOutboxEntries.Clone(),
		withAuditLogs:     _q.withAuditLogs.Clone(),
		withGroupMarkups:  _q.withGroupMarkups.Clone(),
		withSubUsers:      _q.withSubUsers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDomains tells the query-builder to eager-load the nodes that are connected to
// the "domains" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithDomains(opts ...func(*MerchantDomainQuery)) *MerchantQuery {
	query := (&MerchantDomainClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDomains = query
	return _q
}

// WithLedgerEntries tells the query-builder to eager-load the nodes that are connected to
// the "ledger_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithLedgerEntries(opts ...func(*MerchantLedgerQuery)) *MerchantQuery {
	query := (&MerchantLedgerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLedgerEntries = query
	return _q
}

// WithOutboxEntries tells the query-builder to eager-load the nodes that are connected to
// the "outbox_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithOutboxEntries(opts ...func(*MerchantEarningsOutboxQuery)) *MerchantQuery {
	query := (&MerchantEarningsOutboxClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOutboxEntries = query
	return _q
}

// WithAuditLogs tells the query-builder to eager-load the nodes that are connected to
// the "audit_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithAuditLogs(opts ...func(*MerchantAuditLogQuery)) *MerchantQuery {
	query := (&MerchantAuditLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuditLogs = query
	return _q
}

// WithGroupMarkups tells the query-builder to eager-load the nodes that are connected to
// the "group_markups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithGroupMarkups(opts ...func(*MerchantGroupMarkupQuery)) *MerchantQuery {
	query := (&MerchantGroupMarkupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroupMarkups = query
	return _q
}

// WithSubUsers tells the query-builder to eager-load the nodes that are connected to
// the "sub_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MerchantQuery) WithSubUsers(opts ...func(*UserQuery)) *MerchantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubUsers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Merchant.Query().
//		GroupBy(merchant.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MerchantQuery) GroupBy(field string, fields ...string) *MerchantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MerchantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = merchant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Merchant.Query().
//		Select(merchant.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *MerchantQuery) Select(fields ...string) *MerchantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MerchantSelect{MerchantQuery: _q}
	sbuild.label = merchant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MerchantSelect configured with the given aggregations.
func (_q *MerchantQuery) Aggregate(fns ...AggregateFunc) *MerchantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MerchantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !merchant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MerchantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Merchant, error) {
	var (
		nodes       = []*Merchant{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withDomains != nil,
			_q.withLedgerEntries != nil,
			_q.withOutboxEntries != nil,
			_q.withAuditLogs != nil,
			_q.withGroupMarkups != nil,
			_q.withSubUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Merchant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Merchant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDomains; query != nil {
		if err := _q.loadDomains(ctx, query, nodes,
			func(n *Merchant) { n.Edges.Domains = []*MerchantDomain{} },
			func(n *Merchant, e *MerchantDomain) { n.Edges.Domains = append(n.Edges.Domains, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLedgerEntries; query != nil {
		if err := _q.loadLedgerEntries(ctx, query, nodes,
			func(n *Merchant) { n.Edges.LedgerEntries = []*MerchantLedger{} },
			func(n *Merchant, e *MerchantLedger) { n.Edges.LedgerEntries = append(n.Edges.LedgerEntries, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOutboxEntries; query != nil {
		if err := _q.loadOutboxEntries(ctx, query, nodes,
			func(n *Merchant) { n.Edges.OutboxEntries = []*MerchantEarningsOutbox{} },
			func(n *Merchant, e *MerchantEarningsOutbox) { n.Edges.OutboxEntries = append(n.Edges.OutboxEntries, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAuditLogs; query != nil {
		if err := _q.loadAuditLogs(ctx, query, nodes,
			func(n *Merchant) { n.Edges.AuditLogs = []*MerchantAuditLog{} },
			func(n *Merchant, e *MerchantAuditLog) { n.Edges.AuditLogs = append(n.Edges.AuditLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroupMarkups; query != nil {
		if err := _q.loadGroupMarkups(ctx, query, nodes,
			func(n *Merchant) { n.Edges.GroupMarkups = []*MerchantGroupMarkup{} },
			func(n *Merchant, e *MerchantGroupMarkup) { n.Edges.GroupMarkups = append(n.Edges.GroupMarkups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubUsers; query != nil {
		if err := _q.loadSubUsers(ctx, query, nodes,
			func(n *Merchant) { n.Edges.SubUsers = []*User{} },
			func(n *Merchant, e *User) { n.Edges.SubUsers = append(n.Edges.SubUsers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MerchantQuery) loadDomains(ctx context.Context, query *MerchantDomainQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *MerchantDomain)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(merchantdomain.FieldMerchantID)
	}
	query.Where(predicate.MerchantDomain(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.DomainsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MerchantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "merchant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MerchantQuery) loadLedgerEntries(ctx context.Context, query *MerchantLedgerQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *MerchantLedger)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(merchantledger.FieldMerchantID)
	}
	query.Where(predicate.MerchantLedger(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.LedgerEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MerchantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "merchant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MerchantQuery) loadOutboxEntries(ctx context.Context, query *MerchantEarningsOutboxQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *MerchantEarningsOutbox)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(merchantearningsoutbox.FieldMerchantID)
	}
	query.Where(predicate.MerchantEarningsOutbox(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.OutboxEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MerchantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "merchant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MerchantQuery) loadAuditLogs(ctx context.Context, query *MerchantAuditLogQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *MerchantAuditLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(merchantauditlog.FieldMerchantID)
	}
	query.Where(predicate.MerchantAuditLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.AuditLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MerchantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "merchant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MerchantQuery) loadGroupMarkups(ctx context.Context, query *MerchantGroupMarkupQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *MerchantGroupMarkup)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(merchantgroupmarkup.FieldMerchantID)
	}
	query.Where(predicate.MerchantGroupMarkup(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.GroupMarkupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MerchantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "merchant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MerchantQuery) loadSubUsers(ctx context.Context, query *UserQuery, nodes []*Merchant, init func(*Merchant), assign func(*Merchant, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Merchant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(user.FieldParentMerchantID)
	}
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(merchant.SubUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentMerchantID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_merchant_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_merchant_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MerchantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MerchantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(merchant.Table, merchant.Columns, sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchant.FieldID)
		for i := range fields {
			if fields[i] != merchant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MerchantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(merchant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = merchant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *MerchantQuery) ForUpdate(opts ...sql.LockOption) *MerchantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *MerchantQuery) ForShare(opts ...sql.LockOption) *MerchantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// MerchantGroupBy is the group-by builder for Merchant entities.
type MerchantGroupBy struct {
	selector
	build *MerchantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MerchantGroupBy) Aggregate(fns ...AggregateFunc) *MerchantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MerchantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantQuery, *MerchantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MerchantGroupBy) sqlScan(ctx context.Context, root *MerchantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MerchantSelect is the builder for selecting fields of Merchant entities.
type MerchantSelect struct {
	*MerchantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MerchantSelect) Aggregate(fns ...AggregateFunc) *MerchantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MerchantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantQuery, *MerchantSelect](ctx, _s.MerchantQuery, _s, _s.inters, v)
}

func (_s *MerchantSelect) sqlScan(ctx context.Context, root *MerchantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
