// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MerchantLedgerUpdate is the builder for updating MerchantLedger entities.
type MerchantLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *MerchantLedgerMutation
}

// Where appends a list predicates to the MerchantLedgerUpdate builder.
func (_u *MerchantLedgerUpdate) Where(ps ...predicate.MerchantLedger) *MerchantLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *MerchantLedgerUpdate) SetMerchantID(v int64) *MerchantLedgerUpdate {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableMerchantID(v *int64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *MerchantLedgerUpdate) SetOwnerUserID(v int64) *MerchantLedgerUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableOwnerUserID(v *int64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *MerchantLedgerUpdate) AddOwnerUserID(v int64) *MerchantLedgerUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetCounterpartyUserID sets the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdate) SetCounterpartyUserID(v int64) *MerchantLedgerUpdate {
	_u.mutation.ResetCounterpartyUserID()
	_u.mutation.SetCounterpartyUserID(v)
	return _u
}

// SetNillableCounterpartyUserID sets the "counterparty_user_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableCounterpartyUserID(v *int64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetCounterpartyUserID(*v)
	}
	return _u
}

// AddCounterpartyUserID adds value to the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdate) AddCounterpartyUserID(v int64) *MerchantLedgerUpdate {
	_u.mutation.AddCounterpartyUserID(v)
	return _u
}

// ClearCounterpartyUserID clears the value of the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdate) ClearCounterpartyUserID() *MerchantLedgerUpdate {
	_u.mutation.ClearCounterpartyUserID()
	return _u
}

// SetDirection sets the "direction" field.
func (_u *MerchantLedgerUpdate) SetDirection(v string) *MerchantLedgerUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableDirection(v *string) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *MerchantLedgerUpdate) SetAmount(v float64) *MerchantLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableAmount(v *float64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *MerchantLedgerUpdate) AddAmount(v float64) *MerchantLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *MerchantLedgerUpdate) SetBalanceAfter(v float64) *MerchantLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableBalanceAfter(v *float64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *MerchantLedgerUpdate) AddBalanceAfter(v float64) *MerchantLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *MerchantLedgerUpdate) ClearBalanceAfter() *MerchantLedgerUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetIsAggregated sets the "is_aggregated" field.
func (_u *MerchantLedgerUpdate) SetIsAggregated(v bool) *MerchantLedgerUpdate {
	_u.mutation.SetIsAggregated(v)
	return _u
}

// SetNillableIsAggregated sets the "is_aggregated" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableIsAggregated(v *bool) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetIsAggregated(*v)
	}
	return _u
}

// SetAggregatedCount sets the "aggregated_count" field.
func (_u *MerchantLedgerUpdate) SetAggregatedCount(v int) *MerchantLedgerUpdate {
	_u.mutation.ResetAggregatedCount()
	_u.mutation.SetAggregatedCount(v)
	return _u
}

// SetNillableAggregatedCount sets the "aggregated_count" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableAggregatedCount(v *int) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetAggregatedCount(*v)
	}
	return _u
}

// AddAggregatedCount adds value to the "aggregated_count" field.
func (_u *MerchantLedgerUpdate) AddAggregatedCount(v int) *MerchantLedgerUpdate {
	_u.mutation.AddAggregatedCount(v)
	return _u
}

// ClearAggregatedCount clears the value of the "aggregated_count" field.
func (_u *MerchantLedgerUpdate) ClearAggregatedCount() *MerchantLedgerUpdate {
	_u.mutation.ClearAggregatedCount()
	return _u
}

// SetSource sets the "source" field.
func (_u *MerchantLedgerUpdate) SetSource(v string) *MerchantLedgerUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableSource(v *string) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRefType sets the "ref_type" field.
func (_u *MerchantLedgerUpdate) SetRefType(v string) *MerchantLedgerUpdate {
	_u.mutation.SetRefType(v)
	return _u
}

// SetNillableRefType sets the "ref_type" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableRefType(v *string) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetRefType(*v)
	}
	return _u
}

// ClearRefType clears the value of the "ref_type" field.
func (_u *MerchantLedgerUpdate) ClearRefType() *MerchantLedgerUpdate {
	_u.mutation.ClearRefType()
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *MerchantLedgerUpdate) SetRefID(v int64) *MerchantLedgerUpdate {
	_u.mutation.ResetRefID()
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableRefID(v *int64) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// AddRefID adds value to the "ref_id" field.
func (_u *MerchantLedgerUpdate) AddRefID(v int64) *MerchantLedgerUpdate {
	_u.mutation.AddRefID(v)
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *MerchantLedgerUpdate) ClearRefID() *MerchantLedgerUpdate {
	_u.mutation.ClearRefID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *MerchantLedgerUpdate) SetIdempotencyKey(v string) *MerchantLedgerUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableIdempotencyKey(v *string) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *MerchantLedgerUpdate) ClearIdempotencyKey() *MerchantLedgerUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetNote sets the "note" field.
func (_u *MerchantLedgerUpdate) SetNote(v string) *MerchantLedgerUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *MerchantLedgerUpdate) SetNillableNote(v *string) *MerchantLedgerUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *MerchantLedgerUpdate) ClearNote() *MerchantLedgerUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *MerchantLedgerUpdate) SetMerchant(v *Merchant) *MerchantLedgerUpdate {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the MerchantLedgerMutation object of the builder.
func (_u *MerchantLedgerUpdate) Mutation() *MerchantLedgerMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *MerchantLedgerUpdate) ClearMerchant() *MerchantLedgerUpdate {
	_u.mutation.ClearMerchant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MerchantLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MerchantLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MerchantLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MerchantLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MerchantLedgerUpdate) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := merchantledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := merchantledger.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefType(); ok {
		if err := merchantledger.RefTypeValidator(v); err != nil {
			return &ValidationError{Name: "ref_type", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.ref_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := merchantledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantLedger.merchant"`)
	}
	return nil
}

func (_u *MerchantLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantledger.Table, merchantledger.Columns, sqlgraph.NewFieldSpec(merchantledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(merchantledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(merchantledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CounterpartyUserID(); ok {
		_spec.SetField(merchantledger.FieldCounterpartyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCounterpartyUserID(); ok {
		_spec.AddField(merchantledger.FieldCounterpartyUserID, field.TypeInt64, value)
	}
	if _u.mutation.CounterpartyUserIDCleared() {
		_spec.ClearField(merchantledger.FieldCounterpartyUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(merchantledger.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(merchantledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(merchantledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(merchantledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(merchantledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(merchantledger.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsAggregated(); ok {
		_spec.SetField(merchantledger.FieldIsAggregated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AggregatedCount(); ok {
		_spec.SetField(merchantledger.FieldAggregatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAggregatedCount(); ok {
		_spec.AddField(merchantledger.FieldAggregatedCount, field.TypeInt, value)
	}
	if _u.mutation.AggregatedCountCleared() {
		_spec.ClearField(merchantledger.FieldAggregatedCount, field.TypeInt)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(merchantledger.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefType(); ok {
		_spec.SetField(merchantledger.FieldRefType, field.TypeString, value)
	}
	if _u.mutation.RefTypeCleared() {
		_spec.ClearField(merchantledger.FieldRefType, field.TypeString)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(merchantledger.FieldRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefID(); ok {
		_spec.AddField(merchantledger.FieldRefID, field.TypeInt64, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(merchantledger.FieldRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(merchantledger.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(merchantledger.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(merchantledger.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(merchantledger.FieldNote, field.TypeString)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantledger.MerchantTable,
			Columns: []string{merchantledger.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantledger.MerchantTable,
			Columns: []string{merchantledger.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MerchantLedgerUpdateOne is the builder for updating a single MerchantLedger entity.
type MerchantLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MerchantLedgerMutation
}

// SetMerchantID sets the "merchant_id" field.
func (_u *MerchantLedgerUpdateOne) SetMerchantID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableMerchantID(v *int64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *MerchantLedgerUpdateOne) SetOwnerUserID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableOwnerUserID(v *int64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *MerchantLedgerUpdateOne) AddOwnerUserID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetCounterpartyUserID sets the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdateOne) SetCounterpartyUserID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.ResetCounterpartyUserID()
	_u.mutation.SetCounterpartyUserID(v)
	return _u
}

// SetNillableCounterpartyUserID sets the "counterparty_user_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableCounterpartyUserID(v *int64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetCounterpartyUserID(*v)
	}
	return _u
}

// AddCounterpartyUserID adds value to the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdateOne) AddCounterpartyUserID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.AddCounterpartyUserID(v)
	return _u
}

// ClearCounterpartyUserID clears the value of the "counterparty_user_id" field.
func (_u *MerchantLedgerUpdateOne) ClearCounterpartyUserID() *MerchantLedgerUpdateOne {
	_u.mutation.ClearCounterpartyUserID()
	return _u
}

// SetDirection sets the "direction" field.
func (_u *MerchantLedgerUpdateOne) SetDirection(v string) *MerchantLedgerUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableDirection(v *string) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *MerchantLedgerUpdateOne) SetAmount(v float64) *MerchantLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableAmount(v *float64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *MerchantLedgerUpdateOne) AddAmount(v float64) *MerchantLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *MerchantLedgerUpdateOne) SetBalanceAfter(v float64) *MerchantLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *MerchantLedgerUpdateOne) AddBalanceAfter(v float64) *MerchantLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *MerchantLedgerUpdateOne) ClearBalanceAfter() *MerchantLedgerUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetIsAggregated sets the "is_aggregated" field.
func (_u *MerchantLedgerUpdateOne) SetIsAggregated(v bool) *MerchantLedgerUpdateOne {
	_u.mutation.SetIsAggregated(v)
	return _u
}

// SetNillableIsAggregated sets the "is_aggregated" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableIsAggregated(v *bool) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetIsAggregated(*v)
	}
	return _u
}

// SetAggregatedCount sets the "aggregated_count" field.
func (_u *MerchantLedgerUpdateOne) SetAggregatedCount(v int) *MerchantLedgerUpdateOne {
	_u.mutation.ResetAggregatedCount()
	_u.mutation.SetAggregatedCount(v)
	return _u
}

// SetNillableAggregatedCount sets the "aggregated_count" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableAggregatedCount(v *int) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetAggregatedCount(*v)
	}
	return _u
}

// AddAggregatedCount adds value to the "aggregated_count" field.
func (_u *MerchantLedgerUpdateOne) AddAggregatedCount(v int) *MerchantLedgerUpdateOne {
	_u.mutation.AddAggregatedCount(v)
	return _u
}

// ClearAggregatedCount clears the value of the "aggregated_count" field.
func (_u *MerchantLedgerUpdateOne) ClearAggregatedCount() *MerchantLedgerUpdateOne {
	_u.mutation.ClearAggregatedCount()
	return _u
}

// SetSource sets the "source" field.
func (_u *MerchantLedgerUpdateOne) SetSource(v string) *MerchantLedgerUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableSource(v *string) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRefType sets the "ref_type" field.
func (_u *MerchantLedgerUpdateOne) SetRefType(v string) *MerchantLedgerUpdateOne {
	_u.mutation.SetRefType(v)
	return _u
}

// SetNillableRefType sets the "ref_type" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableRefType(v *string) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetRefType(*v)
	}
	return _u
}

// ClearRefType clears the value of the "ref_type" field.
func (_u *MerchantLedgerUpdateOne) ClearRefType() *MerchantLedgerUpdateOne {
	_u.mutation.ClearRefType()
	return _u
}

// SetRefID sets the "ref_id" field.
func (_u *MerchantLedgerUpdateOne) SetRefID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.ResetRefID()
	_u.mutation.SetRefID(v)
	return _u
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableRefID(v *int64) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetRefID(*v)
	}
	return _u
}

// AddRefID adds value to the "ref_id" field.
func (_u *MerchantLedgerUpdateOne) AddRefID(v int64) *MerchantLedgerUpdateOne {
	_u.mutation.AddRefID(v)
	return _u
}

// ClearRefID clears the value of the "ref_id" field.
func (_u *MerchantLedgerUpdateOne) ClearRefID() *MerchantLedgerUpdateOne {
	_u.mutation.ClearRefID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *MerchantLedgerUpdateOne) SetIdempotencyKey(v string) *MerchantLedgerUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableIdempotencyKey(v *string) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *MerchantLedgerUpdateOne) ClearIdempotencyKey() *MerchantLedgerUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetNote sets the "note" field.
func (_u *MerchantLedgerUpdateOne) SetNote(v string) *MerchantLedgerUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *MerchantLedgerUpdateOne) SetNillableNote(v *string) *MerchantLedgerUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *MerchantLedgerUpdateOne) ClearNote() *MerchantLedgerUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *MerchantLedgerUpdateOne) SetMerchant(v *Merchant) *MerchantLedgerUpdateOne {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the MerchantLedgerMutation object of the builder.
func (_u *MerchantLedgerUpdateOne) Mutation() *MerchantLedgerMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *MerchantLedgerUpdateOne) ClearMerchant() *MerchantLedgerUpdateOne {
	_u.mutation.ClearMerchant()
	return _u
}

// Where appends a list predicates to the MerchantLedgerUpdate builder.
func (_u *MerchantLedgerUpdateOne) Where(ps ...predicate.MerchantLedger) *MerchantLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MerchantLedgerUpdateOne) Select(field string, fields ...string) *MerchantLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MerchantLedger entity.
func (_u *MerchantLedgerUpdateOne) Save(ctx context.Context) (*MerchantLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MerchantLedgerUpdateOne) SaveX(ctx context.Context) *MerchantLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MerchantLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MerchantLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MerchantLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Direction(); ok {
		if err := merchantledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := merchantledger.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefType(); ok {
		if err := merchantledger.RefTypeValidator(v); err != nil {
			return &ValidationError{Name: "ref_type", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.ref_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := merchantledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "MerchantLedger.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantLedger.merchant"`)
	}
	return nil
}

func (_u *MerchantLedgerUpdateOne) sqlSave(ctx context.Context) (_node *MerchantLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantledger.Table, merchantledger.Columns, sqlgraph.NewFieldSpec(merchantledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MerchantLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchantledger.FieldID)
		for _, f := range fields {
			if !merchantledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != merchantledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(merchantledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(merchantledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CounterpartyUserID(); ok {
		_spec.SetField(merchantledger.FieldCounterpartyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCounterpartyUserID(); ok {
		_spec.AddField(merchantledger.FieldCounterpartyUserID, field.TypeInt64, value)
	}
	if _u.mutation.CounterpartyUserIDCleared() {
		_spec.ClearField(merchantledger.FieldCounterpartyUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(merchantledger.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(merchantledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(merchantledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(merchantledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(merchantledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(merchantledger.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsAggregated(); ok {
		_spec.SetField(merchantledger.FieldIsAggregated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AggregatedCount(); ok {
		_spec.SetField(merchantledger.FieldAggregatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAggregatedCount(); ok {
		_spec.AddField(merchantledger.FieldAggregatedCount, field.TypeInt, value)
	}
	if _u.mutation.AggregatedCountCleared() {
		_spec.ClearField(merchantledger.FieldAggregatedCount, field.TypeInt)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(merchantledger.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefType(); ok {
		_spec.SetField(merchantledger.FieldRefType, field.TypeString, value)
	}
	if _u.mutation.RefTypeCleared() {
		_spec.ClearField(merchantledger.FieldRefType, field.TypeString)
	}
	if value, ok := _u.mutation.RefID(); ok {
		_spec.SetField(merchantledger.FieldRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefID(); ok {
		_spec.AddField(merchantledger.FieldRefID, field.TypeInt64, value)
	}
	if _u.mutation.RefIDCleared() {
		_spec.ClearField(merchantledger.FieldRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(merchantledger.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(merchantledger.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(merchantledger.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(merchantledger.FieldNote, field.TypeString)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantledger.MerchantTable,
			Columns: []string{merchantledger.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantledger.MerchantTable,
			Columns: []string{merchantledger.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MerchantLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
