// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantgroupmarkup"
)

// MerchantGroupMarkupCreate is the builder for creating a MerchantGroupMarkup entity.
type MerchantGroupMarkupCreate struct {
	config
	mutation *MerchantGroupMarkupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MerchantGroupMarkupCreate) SetCreatedAt(v time.Time) *MerchantGroupMarkupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MerchantGroupMarkupCreate) SetNillableCreatedAt(v *time.Time) *MerchantGroupMarkupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MerchantGroupMarkupCreate) SetUpdatedAt(v time.Time) *MerchantGroupMarkupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MerchantGroupMarkupCreate) SetNillableUpdatedAt(v *time.Time) *MerchantGroupMarkupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *MerchantGroupMarkupCreate) SetMerchantID(v int64) *MerchantGroupMarkupCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *MerchantGroupMarkupCreate) SetGroupID(v int64) *MerchantGroupMarkupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSellRate sets the "sell_rate" field.
func (_c *MerchantGroupMarkupCreate) SetSellRate(v float64) *MerchantGroupMarkupCreate {
	_c.mutation.SetSellRate(v)
	return _c
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_c *MerchantGroupMarkupCreate) SetMerchant(v *Merchant) *MerchantGroupMarkupCreate {
	return _c.SetMerchantID(v.ID)
}

// Mutation returns the MerchantGroupMarkupMutation object of the builder.
func (_c *MerchantGroupMarkupCreate) Mutation() *MerchantGroupMarkupMutation {
	return _c.mutation
}

// Save creates the MerchantGroupMarkup in the database.
func (_c *MerchantGroupMarkupCreate) Save(ctx context.Context) (*MerchantGroupMarkup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MerchantGroupMarkupCreate) SaveX(ctx context.Context) *MerchantGroupMarkup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantGroupMarkupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantGroupMarkupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MerchantGroupMarkupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := merchantgroupmarkup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := merchantgroupmarkup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MerchantGroupMarkupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MerchantGroupMarkup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MerchantGroupMarkup.updated_at"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "MerchantGroupMarkup.merchant_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "MerchantGroupMarkup.group_id"`)}
	}
	if _, ok := _c.mutation.SellRate(); !ok {
		return &ValidationError{Name: "sell_rate", err: errors.New(`ent: missing required field "MerchantGroupMarkup.sell_rate"`)}
	}
	if len(_c.mutation.MerchantIDs()) == 0 {
		return &ValidationError{Name: "merchant", err: errors.New(`ent: missing required edge "MerchantGroupMarkup.merchant"`)}
	}
	return nil
}

func (_c *MerchantGroupMarkupCreate) sqlSave(ctx context.Context) (*MerchantGroupMarkup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MerchantGroupMarkupCreate) createSpec() (*MerchantGroupMarkup, *sqlgraph.CreateSpec) {
	var (
		_node = &MerchantGroupMarkup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(merchantgroupmarkup.Table, sqlgraph.NewFieldSpec(merchantgroupmarkup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(merchantgroupmarkup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantgroupmarkup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(merchantgroupmarkup.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.SellRate(); ok {
		_spec.SetField(merchantgroupmarkup.FieldSellRate, field.TypeFloat64, value)
		_node.SellRate = value
	}
	if nodes := _c.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   merchantgroupmarkup.MerchantTable,
			Columns: []string{merchantgroupmarkup.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MerchantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantGroupMarkup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantGroupMarkupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantGroupMarkupCreate) OnConflict(opts ...sql.ConflictOption) *MerchantGroupMarkupUpsertOne {
	_c.conflict = opts
	return &MerchantGroupMarkupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantGroupMarkupCreate) OnConflictColumns(columns ...string) *MerchantGroupMarkupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantGroupMarkupUpsertOne{
		create: _c,
	}
}

type (
	// MerchantGroupMarkupUpsertOne is the builder for "upsert"-ing
	//  one MerchantGroupMarkup node.
	MerchantGroupMarkupUpsertOne struct {
		create *MerchantGroupMarkupCreate
	}

	// MerchantGroupMarkupUpsert is the "OnConflict" setter.
	MerchantGroupMarkupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantGroupMarkupUpsert) SetUpdatedAt(v time.Time) *MerchantGroupMarkupUpsert {
	u.Set(merchantgroupmarkup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsert) UpdateUpdatedAt() *MerchantGroupMarkupUpsert {
	u.SetExcluded(merchantgroupmarkup.FieldUpdatedAt)
	return u
}

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantGroupMarkupUpsert) SetMerchantID(v int64) *MerchantGroupMarkupUpsert {
	u.Set(merchantgroupmarkup.FieldMerchantID, v)
	return u
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsert) UpdateMerchantID() *MerchantGroupMarkupUpsert {
	u.SetExcluded(merchantgroupmarkup.FieldMerchantID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *MerchantGroupMarkupUpsert) SetGroupID(v int64) *MerchantGroupMarkupUpsert {
	u.Set(merchantgroupmarkup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsert) UpdateGroupID() *MerchantGroupMarkupUpsert {
	u.SetExcluded(merchantgroupmarkup.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *MerchantGroupMarkupUpsert) AddGroupID(v int64) *MerchantGroupMarkupUpsert {
	u.Add(merchantgroupmarkup.FieldGroupID, v)
	return u
}

// SetSellRate sets the "sell_rate" field.
func (u *MerchantGroupMarkupUpsert) SetSellRate(v float64) *MerchantGroupMarkupUpsert {
	u.Set(merchantgroupmarkup.FieldSellRate, v)
	return u
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsert) UpdateSellRate() *MerchantGroupMarkupUpsert {
	u.SetExcluded(merchantgroupmarkup.FieldSellRate)
	return u
}

// AddSellRate adds v to the "sell_rate" field.
func (u *MerchantGroupMarkupUpsert) AddSellRate(v float64) *MerchantGroupMarkupUpsert {
	u.Add(merchantgroupmarkup.FieldSellRate, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantGroupMarkupUpsertOne) UpdateNewValues() *MerchantGroupMarkupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(merchantgroupmarkup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MerchantGroupMarkupUpsertOne) Ignore() *MerchantGroupMarkupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantGroupMarkupUpsertOne) DoNothing() *MerchantGroupMarkupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantGroupMarkupCreate.OnConflict
// documentation for more info.
func (u *MerchantGroupMarkupUpsertOne) Update(set func(*MerchantGroupMarkupUpsert)) *MerchantGroupMarkupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantGroupMarkupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantGroupMarkupUpsertOne) SetUpdatedAt(v time.Time) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertOne) UpdateUpdatedAt() *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantGroupMarkupUpsertOne) SetMerchantID(v int64) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetMerchantID(v)
	})
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertOne) UpdateMerchantID() *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateMerchantID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MerchantGroupMarkupUpsertOne) SetGroupID(v int64) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MerchantGroupMarkupUpsertOne) AddGroupID(v int64) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertOne) UpdateGroupID() *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateGroupID()
	})
}

// SetSellRate sets the "sell_rate" field.
func (u *MerchantGroupMarkupUpsertOne) SetSellRate(v float64) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetSellRate(v)
	})
}

// AddSellRate adds v to the "sell_rate" field.
func (u *MerchantGroupMarkupUpsertOne) AddSellRate(v float64) *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.AddSellRate(v)
	})
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertOne) UpdateSellRate() *MerchantGroupMarkupUpsertOne {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateSellRate()
	})
}

// Exec executes the query.
func (u *MerchantGroupMarkupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantGroupMarkupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantGroupMarkupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MerchantGroupMarkupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MerchantGroupMarkupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MerchantGroupMarkupCreateBulk is the builder for creating many MerchantGroupMarkup entities in bulk.
type MerchantGroupMarkupCreateBulk struct {
	config
	err      error
	builders []*MerchantGroupMarkupCreate
	conflict []sql.ConflictOption
}

// Save creates the MerchantGroupMarkup entities in the database.
func (_c *MerchantGroupMarkupCreateBulk) Save(ctx context.Context) ([]*MerchantGroupMarkup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MerchantGroupMarkup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantGroupMarkupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MerchantGroupMarkupCreateBulk) SaveX(ctx context.Context) []*MerchantGroupMarkup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantGroupMarkupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantGroupMarkupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantGroupMarkup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantGroupMarkupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MerchantGroupMarkupCreateBulk) OnConflict(opts ...sql.ConflictOption) *MerchantGroupMarkupUpsertBulk {
	_c.conflict = opts
	return &MerchantGroupMarkupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MerchantGroupMarkupCreateBulk) OnConflictColumns(columns ...string) *MerchantGroupMarkupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MerchantGroupMarkupUpsertBulk{
		create: _c,
	}
}

// MerchantGroupMarkupUpsertBulk is the builder for "upsert"-ing
// a bulk of MerchantGroupMarkup nodes.
type MerchantGroupMarkupUpsertBulk struct {
	create *MerchantGroupMarkupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MerchantGroupMarkupUpsertBulk) UpdateNewValues() *MerchantGroupMarkupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(merchantgroupmarkup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantGroupMarkup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MerchantGroupMarkupUpsertBulk) Ignore() *MerchantGroupMarkupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantGroupMarkupUpsertBulk) DoNothing() *MerchantGroupMarkupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantGroupMarkupCreateBulk.OnConflict
// documentation for more info.
func (u *MerchantGroupMarkupUpsertBulk) Update(set func(*MerchantGroupMarkupUpsert)) *MerchantGroupMarkupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantGroupMarkupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantGroupMarkupUpsertBulk) SetUpdatedAt(v time.Time) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertBulk) UpdateUpdatedAt() *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMerchantID sets the "merchant_id" field.
func (u *MerchantGroupMarkupUpsertBulk) SetMerchantID(v int64) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetMerchantID(v)
	})
}

// UpdateMerchantID sets the "merchant_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertBulk) UpdateMerchantID() *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateMerchantID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MerchantGroupMarkupUpsertBulk) SetGroupID(v int64) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MerchantGroupMarkupUpsertBulk) AddGroupID(v int64) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertBulk) UpdateGroupID() *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateGroupID()
	})
}

// SetSellRate sets the "sell_rate" field.
func (u *MerchantGroupMarkupUpsertBulk) SetSellRate(v float64) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.SetSellRate(v)
	})
}

// AddSellRate adds v to the "sell_rate" field.
func (u *MerchantGroupMarkupUpsertBulk) AddSellRate(v float64) *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.AddSellRate(v)
	})
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *MerchantGroupMarkupUpsertBulk) UpdateSellRate() *MerchantGroupMarkupUpsertBulk {
	return u.Update(func(s *MerchantGroupMarkupUpsert) {
		s.UpdateSellRate()
	})
}

// Exec executes the query.
func (u *MerchantGroupMarkupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MerchantGroupMarkupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantGroupMarkupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantGroupMarkupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
