// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/merchant"
	"github.com/Wei-Shaw/sub2api/ent/merchantearningsoutbox"
)

// MerchantEarningsOutbox is the model entity for the MerchantEarningsOutbox schema.
type MerchantEarningsOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// 触发该笔分润的 sub_user
	CounterpartyUserID *int64 `json:"counterparty_user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// user_markup_share / user_recharge_share / self_recharge
	Source string `json:"source,omitempty"`
	// usage_billing_dedup / payment_order
	RefType string `json:"ref_type,omitempty"`
	// RefID holds the value of the "ref_id" field.
	RefID int64 `json:"ref_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Processed holds the value of the "processed" field.
	Processed bool `json:"processed,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantEarningsOutboxQuery when eager-loading is set.
	Edges        MerchantEarningsOutboxEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MerchantEarningsOutboxEdges holds the relations/edges for other nodes in the graph.
type MerchantEarningsOutboxEdges struct {
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MerchantOrErr returns the Merchant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantEarningsOutboxEdges) MerchantOrErr() (*Merchant, error) {
	if e.Merchant != nil {
		return e.Merchant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: merchant.Label}
	}
	return nil, &NotLoadedError{edge: "merchant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantEarningsOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantearningsoutbox.FieldProcessed:
			values[i] = new(sql.NullBool)
		case merchantearningsoutbox.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case merchantearningsoutbox.FieldID, merchantearningsoutbox.FieldMerchantID, merchantearningsoutbox.FieldCounterpartyUserID, merchantearningsoutbox.FieldRefID:
			values[i] = new(sql.NullInt64)
		case merchantearningsoutbox.FieldSource, merchantearningsoutbox.FieldRefType, merchantearningsoutbox.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case merchantearningsoutbox.FieldProcessedAt, merchantearningsoutbox.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantEarningsOutbox fields.
func (_m *MerchantEarningsOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantearningsoutbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case merchantearningsoutbox.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.Int64
			}
		case merchantearningsoutbox.FieldCounterpartyUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field counterparty_user_id", values[i])
			} else if value.Valid {
				_m.CounterpartyUserID = new(int64)
				*_m.CounterpartyUserID = value.Int64
			}
		case merchantearningsoutbox.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case merchantearningsoutbox.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case merchantearningsoutbox.FieldRefType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_type", values[i])
			} else if value.Valid {
				_m.RefType = value.String
			}
		case merchantearningsoutbox.FieldRefID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ref_id", values[i])
			} else if value.Valid {
				_m.RefID = value.Int64
			}
		case merchantearningsoutbox.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case merchantearningsoutbox.FieldProcessed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field processed", values[i])
			} else if value.Valid {
				_m.Processed = value.Bool
			}
		case merchantearningsoutbox.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case merchantearningsoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantEarningsOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantEarningsOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMerchant queries the "merchant" edge of the MerchantEarningsOutbox entity.
func (_m *MerchantEarningsOutbox) QueryMerchant() *MerchantQuery {
	return NewMerchantEarningsOutboxClient(_m.config).QueryMerchant(_m)
}

// Update returns a builder for updating this MerchantEarningsOutbox.
// Note that you need to call MerchantEarningsOutbox.Unwrap() before calling this method if this MerchantEarningsOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantEarningsOutbox) Update() *MerchantEarningsOutboxUpdateOne {
	return NewMerchantEarningsOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantEarningsOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantEarningsOutbox) Unwrap() *MerchantEarningsOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantEarningsOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantEarningsOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantEarningsOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MerchantID))
	builder.WriteString(", ")
	if v := _m.CounterpartyUserID; v != nil {
		builder.WriteString("counterparty_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("ref_type=")
	builder.WriteString(_m.RefType)
	builder.WriteString(", ")
	builder.WriteString("ref_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefID))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("processed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Processed))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MerchantEarningsOutboxes is a parsable slice of MerchantEarningsOutbox.
type MerchantEarningsOutboxes []*MerchantEarningsOutbox
