// Code generated by ent, DO NOT EDIT.

package merchantgroupcost

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldUpdatedAt, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldMerchantID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldGroupID, v))
}

// CostRate applies equality check predicate on the "cost_rate" field. It's identical to CostRateEQ.
func CostRate(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldCostRate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLTE(FieldUpdatedAt, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldMerchantID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLTE(FieldGroupID, v))
}

// CostRateEQ applies the EQ predicate on the "cost_rate" field.
func CostRateEQ(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldEQ(FieldCostRate, v))
}

// CostRateNEQ applies the NEQ predicate on the "cost_rate" field.
func CostRateNEQ(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNEQ(FieldCostRate, v))
}

// CostRateIn applies the In predicate on the "cost_rate" field.
func CostRateIn(vs ...float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldIn(FieldCostRate, vs...))
}

// CostRateNotIn applies the NotIn predicate on the "cost_rate" field.
func CostRateNotIn(vs ...float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldNotIn(FieldCostRate, vs...))
}

// CostRateGT applies the GT predicate on the "cost_rate" field.
func CostRateGT(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGT(FieldCostRate, v))
}

// CostRateGTE applies the GTE predicate on the "cost_rate" field.
func CostRateGTE(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldGTE(FieldCostRate, v))
}

// CostRateLT applies the LT predicate on the "cost_rate" field.
func CostRateLT(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLT(FieldCostRate, v))
}

// CostRateLTE applies the LTE predicate on the "cost_rate" field.
func CostRateLTE(v float64) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.FieldLTE(FieldCostRate, v))
}

// HasMerchant applies the HasEdge predicate on the "merchant" edge.
func HasMerchant() predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantWith applies the HasEdge predicate on the "merchant" edge with a given conditions (other predicates).
func HasMerchantWith(preds ...predicate.Merchant) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(func(s *sql.Selector) {
		step := newMerchantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantGroupCost) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantGroupCost) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantGroupCost) predicate.MerchantGroupCost {
	return predicate.MerchantGroupCost(sql.NotPredicates(p))
}
