// Code generated by ent, DO NOT EDIT.

package merchant

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the merchant type in the database.
	Label = "merchant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOwnerBalanceBaseline holds the string denoting the owner_balance_baseline field in the database.
	FieldOwnerBalanceBaseline = "owner_balance_baseline"
	// FieldLowBalanceThreshold holds the string denoting the low_balance_threshold field in the database.
	FieldLowBalanceThreshold = "low_balance_threshold"
	// FieldNotifyEmails holds the string denoting the notify_emails field in the database.
	FieldNotifyEmails = "notify_emails"
	// EdgeDomains holds the string denoting the domains edge name in mutations.
	EdgeDomains = "domains"
	// EdgeLedgerEntries holds the string denoting the ledger_entries edge name in mutations.
	EdgeLedgerEntries = "ledger_entries"
	// EdgeOutboxEntries holds the string denoting the outbox_entries edge name in mutations.
	EdgeOutboxEntries = "outbox_entries"
	// EdgeAuditLogs holds the string denoting the audit_logs edge name in mutations.
	EdgeAuditLogs = "audit_logs"
	// EdgeGroupMarkups holds the string denoting the group_markups edge name in mutations.
	EdgeGroupMarkups = "group_markups"
	// EdgeGroupCosts holds the string denoting the group_costs edge name in mutations.
	EdgeGroupCosts = "group_costs"
	// EdgeWithdrawRequests holds the string denoting the withdraw_requests edge name in mutations.
	EdgeWithdrawRequests = "withdraw_requests"
	// EdgeSubUsers holds the string denoting the sub_users edge name in mutations.
	EdgeSubUsers = "sub_users"
	// Table holds the table name of the merchant in the database.
	Table = "merchants"
	// DomainsTable is the table that holds the domains relation/edge.
	DomainsTable = "merchant_domains"
	// DomainsInverseTable is the table name for the MerchantDomain entity.
	// It exists in this package in order to avoid circular dependency with the "merchantdomain" package.
	DomainsInverseTable = "merchant_domains"
	// DomainsColumn is the table column denoting the domains relation/edge.
	DomainsColumn = "merchant_id"
	// LedgerEntriesTable is the table that holds the ledger_entries relation/edge.
	LedgerEntriesTable = "merchant_ledger"
	// LedgerEntriesInverseTable is the table name for the MerchantLedger entity.
	// It exists in this package in order to avoid circular dependency with the "merchantledger" package.
	LedgerEntriesInverseTable = "merchant_ledger"
	// LedgerEntriesColumn is the table column denoting the ledger_entries relation/edge.
	LedgerEntriesColumn = "merchant_id"
	// OutboxEntriesTable is the table that holds the outbox_entries relation/edge.
	OutboxEntriesTable = "merchant_earnings_outbox"
	// OutboxEntriesInverseTable is the table name for the MerchantEarningsOutbox entity.
	// It exists in this package in order to avoid circular dependency with the "merchantearningsoutbox" package.
	OutboxEntriesInverseTable = "merchant_earnings_outbox"
	// OutboxEntriesColumn is the table column denoting the outbox_entries relation/edge.
	OutboxEntriesColumn = "merchant_id"
	// AuditLogsTable is the table that holds the audit_logs relation/edge.
	AuditLogsTable = "merchant_audit_log"
	// AuditLogsInverseTable is the table name for the MerchantAuditLog entity.
	// It exists in this package in order to avoid circular dependency with the "merchantauditlog" package.
	AuditLogsInverseTable = "merchant_audit_log"
	// AuditLogsColumn is the table column denoting the audit_logs relation/edge.
	AuditLogsColumn = "merchant_id"
	// GroupMarkupsTable is the table that holds the group_markups relation/edge.
	GroupMarkupsTable = "merchant_group_markups"
	// GroupMarkupsInverseTable is the table name for the MerchantGroupMarkup entity.
	// It exists in this package in order to avoid circular dependency with the "merchantgroupmarkup" package.
	GroupMarkupsInverseTable = "merchant_group_markups"
	// GroupMarkupsColumn is the table column denoting the group_markups relation/edge.
	GroupMarkupsColumn = "merchant_id"
	// GroupCostsTable is the table that holds the group_costs relation/edge.
	GroupCostsTable = "merchant_group_costs"
	// GroupCostsInverseTable is the table name for the MerchantGroupCost entity.
	// It exists in this package in order to avoid circular dependency with the "merchantgroupcost" package.
	GroupCostsInverseTable = "merchant_group_costs"
	// GroupCostsColumn is the table column denoting the group_costs relation/edge.
	GroupCostsColumn = "merchant_id"
	// WithdrawRequestsTable is the table that holds the withdraw_requests relation/edge.
	WithdrawRequestsTable = "merchant_withdraw_requests"
	// WithdrawRequestsInverseTable is the table name for the MerchantWithdrawRequest entity.
	// It exists in this package in order to avoid circular dependency with the "merchantwithdrawrequest" package.
	WithdrawRequestsInverseTable = "merchant_withdraw_requests"
	// WithdrawRequestsColumn is the table column denoting the withdraw_requests relation/edge.
	WithdrawRequestsColumn = "merchant_id"
	// SubUsersTable is the table that holds the sub_users relation/edge.
	SubUsersTable = "users"
	// SubUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SubUsersInverseTable = "users"
	// SubUsersColumn is the table column denoting the sub_users relation/edge.
	SubUsersColumn = "parent_merchant_id"
)

// Columns holds all SQL columns for merchant fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOwnerUserID,
	FieldName,
	FieldStatus,
	FieldOwnerBalanceBaseline,
	FieldLowBalanceThreshold,
	FieldNotifyEmails,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultOwnerBalanceBaseline holds the default value on creation for the "owner_balance_baseline" field.
	DefaultOwnerBalanceBaseline float64
	// DefaultLowBalanceThreshold holds the default value on creation for the "low_balance_threshold" field.
	DefaultLowBalanceThreshold float64
	// DefaultNotifyEmails holds the default value on creation for the "notify_emails" field.
	DefaultNotifyEmails []string
)

// OrderOption defines the ordering options for the Merchant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOwnerBalanceBaseline orders the results by the owner_balance_baseline field.
func ByOwnerBalanceBaseline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerBalanceBaseline, opts...).ToFunc()
}

// ByLowBalanceThreshold orders the results by the low_balance_threshold field.
func ByLowBalanceThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLowBalanceThreshold, opts...).ToFunc()
}

// ByDomainsCount orders the results by domains count.
func ByDomainsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDomainsStep(), opts...)
	}
}

// ByDomains orders the results by domains terms.
func ByDomains(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLedgerEntriesCount orders the results by ledger_entries count.
func ByLedgerEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLedgerEntriesStep(), opts...)
	}
}

// ByLedgerEntries orders the results by ledger_entries terms.
func ByLedgerEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOutboxEntriesCount orders the results by outbox_entries count.
func ByOutboxEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutboxEntriesStep(), opts...)
	}
}

// ByOutboxEntries orders the results by outbox_entries terms.
func ByOutboxEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutboxEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuditLogsCount orders the results by audit_logs count.
func ByAuditLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuditLogsStep(), opts...)
	}
}

// ByAuditLogs orders the results by audit_logs terms.
func ByAuditLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupMarkupsCount orders the results by group_markups count.
func ByGroupMarkupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupMarkupsStep(), opts...)
	}
}

// ByGroupMarkups orders the results by group_markups terms.
func ByGroupMarkups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupMarkupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupCostsCount orders the results by group_costs count.
func ByGroupCostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupCostsStep(), opts...)
	}
}

// ByGroupCosts orders the results by group_costs terms.
func ByGroupCosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupCostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWithdrawRequestsCount orders the results by withdraw_requests count.
func ByWithdrawRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWithdrawRequestsStep(), opts...)
	}
}

// ByWithdrawRequests orders the results by withdraw_requests terms.
func ByWithdrawRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWithdrawRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubUsersCount orders the results by sub_users count.
func BySubUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubUsersStep(), opts...)
	}
}

// BySubUsers orders the results by sub_users terms.
func BySubUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDomainsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DomainsTable, DomainsColumn),
	)
}
func newLedgerEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
	)
}
func newOutboxEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutboxEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutboxEntriesTable, OutboxEntriesColumn),
	)
}
func newAuditLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
	)
}
func newGroupMarkupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupMarkupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupMarkupsTable, GroupMarkupsColumn),
	)
}
func newGroupCostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupCostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupCostsTable, GroupCostsColumn),
	)
}
func newWithdrawRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WithdrawRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WithdrawRequestsTable, WithdrawRequestsColumn),
	)
}
func newSubUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubUsersTable, SubUsersColumn),
	)
}
